# PEFT(Parameter Efficient Fine-tuning)

딥러닝 모델의 크기가 증가함에 따라, 기존과 같이 태스크에 따른 모델 튜닝에 있어 기존과 같이 모든 파라미터를 미세조정하는 full-fine-tuning 방식은 자원 측면에서 점점 불가능해지고 있다.

이에 파라미터 효율적으로 fine-tuning 하는 PEFT 방법이 활발하게 연구되고 있다.

- PEFT는 다운스트림 작업의 성능을 유지하거나 심지어 향상시키면서 학습에 필요한 계산량, 혹은 모델의 크기를 줄이는 것을 목표로 한다.



PEFT는 아래와 같은 장점을 가진다:


✔ 필요한 계산량의 감소: 모델 크기를 줄이고, 중복된 파라미터를 제거하며 정밀도를 낮춤으로써 연산량을 줄인다.

✔ 추론 속도의 향상: 모델 크기가 작아지고 계산 복잡도가 줄어듬에 따라 추론 속도가 감소하여 실시간 애플리케이션에 적합해진다.

✔ 리소스가 제한된 디바이스에서의 배포 개선: 모바일 디바이스나 엣지 디바이스와 같이 제한적인 시소스에의 배포가 용이해진다.

✔  비용 절감: fine-tuning 및 추론에 드는 모든 비용이 절감된다

✔ 선응 유지 혹은 향상: 모델 크기가 줄어들면서도 다운스트림 태스크에의 성능을 유지하거나 향상하는 것이 가능하다.

### 대표적인 PEFT 방법론 6가지

1. 지식증류(Knowledge distillation)
- 지식 증류(knowledge distrystal)는 지식을 크고 성과가 좋은 모델(teacher)에서 더 작은 모델(student)로 전달하는 기술이다. Teacher 모델의 output probability를 student 모델 학습을 위한 소프트 타깃(soft target)으로 사용한다.

- 이 과정은 student 모델이 teacher 모델이 학습한 방대한 지식을 얻을 뿐만 아니라, 일반화를 더 잘할 수 있도록 한다. 모델 크기를 줄일 뿐만 아니라 더 작은 student 모델이 정규화(regularize)하도록 도움을 주는 것이다.  



2. 모델 가지치기(Pruning)
- 가지치기는 사전 학습된 모델에서 불필요한 가중치나 연결을 제거하는 기법이다. 중복되거나 덜 중요한 매개변수를 식별하고 제거함으로써 모델의 크기와 계산 요구 사항을 크게 줄일 수 있다. Magnitude-based pruning(크기가 작은 가중치를 제거함), Structured pruning(중요도에 따라 특정 뉴런 또는 필터를 제거) 등 다양한 방법이 존재하며, 성능 저하 없이 중복 매개변수를 제거하여 효율적으로 fine-tuning 할 수 있다.



3. 양자화 (Quantization)
- 양자화는 모델 매개변수(가중치)의 정밀도를 낮춰 메모리 및 계산 요구 사항을 낮추는 기술이다다. 기존 딥러닝 모델에서 매개변수는 일반적으로 32비트 부동 소수점 숫자로 저장된다. 하지만 양자화를 사용하면 이러한 매개변수를 8비트 정수와 같이 더 낮은 비트 정밀도로 표현할 수 있다. 이렇게 정밀도를 낮추면 메모리 사용량이 크게 줄어들고 계산 속도가 빨라진다.

- 양자화는 학습 후 사전 학습된 모델을 양자화하는 post-training quantization 기법과 양자화를 염두에 두고 모델을 학습하는 quantization-aware training으로 나뉜다. 두 가지 접근 방식 모두 모델 성능을 유지하면서 효율적인 fine-tuning을 수행한다.



4. Low Rank Factorization
- Low-rank factorization은 사전학습된 모델의 가중치 행렬을 row-rank 행렬로 근사화하는 기술이다. 가중치 행렬을 저순위 구성 요소로 분해함으로써 모델의 매개 변수 수와 계산 복잡도를 줄인다. 단수 값 분해(SVD) 및 텐서 인수분해와 같은 low-rank factoraization 방법은 모델이 수행해야 하는 태스크에서 가장 중요한 정보를 유지하는 low-rank 근사치를 찾는 것을 목표로 한다. 이 기술은 합리적인 성능을 달성하면서 매개 변수 효율적인 미세 조정 옵션을 제공한다.



5. 지식 주입(Knowledge Injection)
- 지식 주입은 원래 모델의 파라미터를 수정하지 않고, 태스크 별 정보를 주입함으로써 특정 태스크에 대한 사전 학습된 모델의 성능을 향상시키는 기술이다. 이는 태스크별 모듈을 추가하거나 기존 아키텍처를 수정하여 태스크별 feature을 학습할 수 있도록 구현한다. 지식 주입은 사전 학습된 모델에 이미 존재하는 지식을 활용하면서도 재학습의 필요성을 최소화하기 때문에 효율적인 fine-tuning이 가능하다. 원본 모델에 대한 수정을 최소화하고자 하는 시나리오에서 특히 유용한 방법론이다.



6. Adapter Modules(어댑터 모듈)
- 어댑터 모듈은 원래의 파라미터를 수정하지 않고 특정 작업을 위해 사전 학습된 모델에 추가하는 경량 모듈을 말한다. 이 모듈은 태스크별로 관리해야 하며, 사전 학습된 모델의 아키텍처의 각기 다른 계층에 삽입하는 것이 가능하다. 어댑터 모듈은 사전 학습된 파라미터의 대부분을 그대로 유지하면서 모델이 작업별 정보를 학습할 수 있도록 함으로써 효율적인 미세 조정이 가능하도록 한다. 이 접근 방식은 전체 모델을 재학습하지 않고도 어댑터를 다른 태스크들에 대해 쉽게 추가하거나 제거할 수 있으므로 유연성과 효율성을 제공한다.

# LoRA란?

LoRA는 **Low-Rank Adaptation**의 줄임말로, 대규모 언어모델(LLM)을 **전체 다 다시 학습하지 않고**,  
일부 작은 파라미터만 추가로 학습해서 미세조정(fine-tuning)하는 방법.

기존 모델 전체를 뜯어고치는 대신**작은 보정 장치만 붙여서 학습하는 방식**.

---

# 왜 LoRA가 필요한가?

대형 모델은 파라미터 수가 매우 많음.  
예를 들어 수억 개, 수십억 개 파라미터를 가진 모델을 그대로 fine-tuning 하려면:

- GPU 메모리가 많이 필요함
- 학습 시간이 오래 걸림
- 저장 공간이 큼
- 실습 환경에서는 부담이 큼

LoRA는 이 문제를 줄이기 위해 나왔습니다.



- **전체 모델은 그대로 두고**
- **아주 작은 부분만 학습해서**
- **적은 자원으로도 fine-tuning 가능하게 하는 방법**

---

# 핵심 아이디어

원래 신경망의 가중치 행렬을 $ W $라고 하겠습니다.

보통 full fine-tuning은 이 $ W $ 자체를 직접 업데이트합니다.

하지만 LoRA는 $ W $를 그대로 두고, 작은 두 행렬 $ A $, $ B $를 추가해서 다음처럼 바꿉니다.

$$
W' = W + \Delta W
$$

여기서

$$
\Delta W = BA
$$


$$
W' = W + BA
$$

가 됩니다.

---

# 수식의 의미

- $ W $: 원래 모델의 가중치
- $ A $, $ B $: 새로 추가하는 작은 학습 파라미터
- $ BA $: 원래 가중치에 더해지는 보정값

핵심은 $ BA $가 **저랭크(low-rank)** 구조라는 점입니다.

큰 행렬 전체를 직접 학습하는 대신 더 작은 차원으로 압축된 변화량만 학습합니다.

그래서 학습해야 할 파라미터 수가 크게 줄어듬.

---

# 왜 "Low-Rank"인가?

행렬의 랭크(rank)는 그 행렬이 담고 있는 정보의 독립적인 차원 수를 뜻합니다.

LoRA에서는 변화량 $ \Delta W $를  
작은 랭크 $ r $를 가진 두 행렬의 곱으로 표현.

예를 들어 원래 $ W $가 $ d \times k $ 크기라면,  
LoRA는 보통 다음처럼 둡니다.

$$
A \in \mathbb{R}^{r \times k}, \quad B \in \mathbb{R}^{d \times r}
$$

그러면

$$
BA \in \mathbb{R}^{d \times k}
$$

가 되어 원래 $ W $와 같은 크기의 보정값을 만들 수 있습니다.

여기서 $ r $은 보통 $ d $나 $ k $보다 훨씬 작습니다.


큰 변화를 직접 저장하지 않고 **작은 차원의 압축된 형태로 저장**.

---

# Full Fine-Tuning과 LoRA 비교

## 1. Full Fine-Tuning

모델의 모든 파라미터를 업데이트합니다.

### 장점
- 충분한 자원이 있으면 높은 성능을 낼 수 있음
- 모델 전체를 작업에 맞게 바꿀 수 있음

### 단점
- 메모리 사용량이 큼
- 학습 시간이 오래 걸림
- 저장해야 할 파인튜닝 모델 크기도 큼

---

## 2. LoRA Fine-Tuning

원래 모델 가중치는 고정하고, 추가한 작은 행렬만 학습합니다.

### 장점
- 메모리를 적게 사용
- 학습 속도가 빠름
- 여러 태스크별 adapter를 따로 저장 가능
- 실습, 연구 초기 단계, 제한된 GPU 환경에 적합

### 단점
- 경우에 따라 full fine-tuning보다 표현력이 제한될 수 있음
- 어떤 층에 적용할지에 따라 성능 차이가 날 수 있음

---

# LoRA가 특히 좋은 이유

LoRA가 많이 쓰이는 이유는 다음과 같음.

## 1. 가볍다
큰 모델 전체를 학습하지 않으므로 GPU 메모리를 적게 씁니다.

## 2. 빠르다
학습해야 하는 파라미터 수가 적어서 업데이트가 빠릅니다.

## 3. 저장이 효율적이다
모델 전체를 새로 저장하지 않고, LoRA 파라미터만 저장하면 됩니다.

## 4. 여러 작업에 쉽게 대응 가능하다
하나의 base model 위에 태스크별로 다른 LoRA adapter를 붙여 사용할 수 있습니다.

예를 들어:

- 발표문 스타일 LoRA
- 요약용 LoRA
- 질의응답용 LoRA
- 번역용 LoRA

처럼 분리할 수 있음.

---

# Transformer에서 어디에 적용하나?

LoRA는 보통 Transformer의 **선형층(linear layer)** 에 적용합니다.  
특히 attention 관련 projection 층에 자주 적용합니다.

예를 들어:

- `q_proj`
- `k_proj`
- `v_proj`
- `o_proj`

같은 부분입니다.

---

# 왜 attention 쪽에 많이 적용하나?

attention은 Transformer의 핵심 연산.  

문장 안에서 어떤 단어가 다른 단어를 얼마나 참고할지 결정하는 중요한 부분입.

따라서 이 부분을 조금만 조정해도 모델의 응답 스타일이나 특정 작업 성능이 꽤 달라질 수 있습니다.

그래서 실습에서는 보통

```python
target_modules=["q_proj", "v_proj"]

다시 정리하면,

일반적인 선형 변환 가중치 $W$를 직접 전부 업데이트하는 대신, LoRA는 변화량 $\Delta W$를 저차원 행렬 곱 BA 형태로 근사해서 학습함.

원래 가중치는 고정하고 작은 랭크 $r$를 가진 보조 행렬만 학습하는 구조.

Hugging Face PEFT 문서도 LoRA를 low-Rank Decomposition으로 파마티러 수를 줄이는 방법으로 설명

In [1]:
# 라이브러리 설치
!pip install transformers peft datasets accelerate
# GPU 없더라도 아주 작은 모델로는 실습이 가능하지만 속도는 느릴 수 있음.

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.5.3)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.4)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

In [2]:
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,         #모델에 맞는 토크나이저(텍스트를 숫자로 변환)를 자동으로 선택
    AutoModelForCausalLM,  # GPT/Llama 같은 텍스트 생성용 모델을 자동으로 불러옴
    Trainer,               # 복잡한 학습 루프(루프, 검증, 저장 등)를 추상화 하여 실행
    TrainingArguments,     # 학습률, 배치 크기, 저장 경로 등 하이퍼파라미터를 설정함.
    DataCollatorForLanguageModeling, # 데이터를 모델 입력에 맞게 배치(Batch) 단위로 묶어주는 역할
)
from peft import LoraConfig, get_peft_model, TaskType
#LoraConfig: 저랭크 어텝터 학습을 위한 설정값(rank, alpha 등)을 정의
#get_peft_model: 일반 모델에 LoRA 레이러를 추가하여 효율적 학습이 가능한 모델로 변환
# TaskType: 모델의 작업 유형(ex.Causal LM, seq2seq)을 지정하여 최적의 설정을 도움

In [3]:
device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available()
    else "cpu"
)
print("device:", device)

device: cpu

In [4]:
model_name = "distilgpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
    model.config.pad_token_id = tokenizer.eos_token_id

model = model.to(device)
print("loaded:", model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

loaded: distilgpt2

In [5]:
# 학습 전 생성 함수

def generate_text(model, tokenizer, prompt, max_new_tokens=80):
    model.eval()
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

In [6]:
# 학습 전 결과 확인

test_prompt = """Question: What is LoRA?
Answer:"""

print(generate_text(model, tokenizer, test_prompt))

# 우리가 원하는 형식으로 예쁘게 답하지 못함 -> 여기에 LoRA를 붙임.

Question: What is LoRA?
Answer: LoRA is a simple, simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple, and simple,

In [7]:
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,                         # 저랭크 차원. 작을수록 가볍지만 표현력은 줄 수 있음
    lora_alpha=16,               # 업데이트 크기 스케일
    lora_dropout=0.05,           # LoRA 경로에 들어가는 드롭아웃
    target_modules="all-linear", # 어느 선형층에 LoRA를 삽입할지 / 선형/Conv1D 모듈 전체를 대상으로 잡을 수 있음
)

보통 처음에는 $r$=4, 8, 16 정도를 많이 시험.

너무 크게 시작할 필요는 없음. LoRA의 목적 자체가 작은 추가 파라미터로 효율적으로 적응하는 데 있기 때문.

In [8]:
# LoRA 모델 만들기
lora_model = get_peft_model(model, lora_config)
lora_model.print_trainable_parameters()
# trainable params -> 전체 모델 파라미터는 그대로 있지만, 실제 학습되는 것은 매우 일부라는 것이 핵심

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work
/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:2285: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

trainable params: 589,824 || all params: 82,502,400 || trainable%: 0.7149

In [9]:
# 아주 작은 데이터 만들기


train_data = [
    {
        "text": """Question: What is LoRA?
Answer:
Definition: LoRA is a parameter-efficient fine-tuning method.
Key point: It freezes the base model and trains small low-rank adapters.
Example: You can adapt a language model without updating all weights."""
    },
    {
        "text": """Question: What is quantization?
Answer:
Definition: Quantization is the process of using lower-precision numbers for model weights.
Key point: It reduces memory usage and can speed up inference.
Example: A model can be stored in 8-bit or 4-bit instead of 16-bit."""
    },
    {
        "text": """Question: What is overfitting?
Answer:
Definition: Overfitting means a model learns training data too specifically.
Key point: It performs well on training data but poorly on new data.
Example: A model memorizes examples instead of learning general patterns."""
    },
    {
        "text": """Question: What is gradient descent?
Answer:
Definition: Gradient descent is an optimization method for reducing loss.
Key point: It updates parameters in the direction that lowers error.
Example: Neural networks use gradient descent during training."""
    },
    {
        "text": """Question: What is a tokenizer?
Answer:
Definition: A tokenizer converts text into tokens.
Key point: Models process token IDs instead of raw strings.
Example: A sentence can be split into words, subwords, or characters."""
    },
    {
        "text": """Question: What is transfer learning?
Answer:
Definition: Transfer learning reuses knowledge from a pretrained model.
Key point: It helps solve a new task with less data.
Example: A pretrained language model can be adapted for summarization."""
    },
    {
        "text": """Question: What is a transformer?
Answer:
Definition: A transformer is a neural architecture based on attention.
Key point: It models relationships between tokens efficiently.
Example: GPT and BERT are based on transformer blocks."""
    },
    {
        "text": """Question: What is fine-tuning?
Answer:
Definition: Fine-tuning is continued training of a pretrained model on a new task.
Key point: It adapts the model to a domain or objective.
Example: A general model can be fine-tuned for customer support replies."""
    },
    {
        "text": """Question: What is LoRA used for?
Answer:
Definition: LoRA is used for efficient model adaptation.
Key point: It reduces the number of trainable parameters.
Example: You can personalize a model with limited GPU memory."""
    },
    {
        "text": """Question: Why is LoRA useful?
Answer:
Definition: LoRA is useful because it makes fine-tuning lighter.
Key point: It saves memory and storage compared with full fine-tuning.
Example: Multiple small adapters can be stored for different tasks."""
    },
]

In [10]:
# Dataset 변환

dataset = Dataset.from_list(train_data)

def tokenize_fn(example):
    out = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128,
    )
    out["labels"] = out["input_ids"].copy()
    return out

tokenized_dataset = dataset.map(tokenize_fn)
tokenized_dataset = tokenized_dataset.remove_columns(["text"])

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

In [11]:
# data collator
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

In [13]:
# 학습 설정
training_args = TrainingArguments(
    output_dir="./lora_demo_output",
    # overwrite_output_dir=True,
    num_train_epochs=30,
    per_device_train_batch_size=2,
    logging_steps=1,
    save_strategy="no",
    report_to="none",
    learning_rate=1e-3,
)

#requires_grad=True 인 adapter 파라미터만 업데이트

In [14]:
# Trainer 구성 및 학습

trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator,
)

trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

TrainOutput(global_step=150, training_loss=0.9411354169249535, metrics={'train_runtime': 405.1659, 'train_samples_per_second': 0.74, 'train_steps_per_second': 0.37, 'total_flos': 9934523596800.0, 'train_loss': 0.9411354169249535, 'epoch': 30.0})

In [15]:
# 학습 후 결과 확인

prompts = [
    """Question: What is LoRA?
Answer:""",
    """Question: What is attention?
Answer:""",
    """Question: What is regularization?
Answer:"""
]

for p in prompts:
    print("=" * 80)
    print(generate_text(lora_model, tokenizer, p))
    print()

================================================================================
Question: What is LoRA?
Answer:
Definition: LoRA is a parameter-efficient fine-tuning method.
Key point: It freezes the base model and trains small low-rank adapters.
Example: You can adapt a language model without updating all weights.
Example: You can adapt a language model without updating all weights.
Example: You can adapt a language model without updating all weights.
Example: You can

================================================================================
Question: What is attention?
Answer:
Definition: Attention is a tokenizer and a pretrained model.
Key point: It models relationships between tokens efficiently.
Example: A pretrained language model can be adapted for summarization.
Example: A pretrained language can be adapted for summarization.
Example: A pretrained language can be adapted for summarization.
Example: A pretrained language can be adapted for summar

================================================================================
Question: What is regularization?
Answer:
Definition: Regularization is the process of using lower-precision numbers for model weights.
Key point: It updates weights without updating weights.
Example: A model can be stored in 8-bit or 4-bit instead of 16-bit.
Example: A model can be stored for example in 16-bit or 4-bit instead of 16-bit.
Example: A

In [16]:
# 저장
lora_model.save_pretrained("./my_lora_adapter")
tokenizer.save_pretrained("./my_lora_adapter")

('./my_lora_adapter/tokenizer_config.json', './my_lora_adapter/tokenizer.json')

#### LoRA가 어디에 붙는지 해부

“LoRA가 모델 전체를 바꾸는 게 아니라, 일부 선형층에 작은 저랭크 행렬만 추가"

In [17]:
!pip install -q transformers peft accelerate datasets

In [18]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model

model_id = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype="auto",
    device_map="auto"
)

config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
    bias="none",
    task_type="CAUSAL_LM"
)

lora_model = get_peft_model(model, config)
lora_model.print_trainable_parameters()

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

trainable params: 1,089,536 || all params: 1,544,803,840 || trainable%: 0.0705

In [19]:
# 붙은 모듈 확인
for name, module in lora_model.named_modules():
    if "lora" in name.lower():
        print(name)

base_model.model.model.layers.0.self_attn.q_proj.lora_dropout
base_model.model.model.layers.0.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.0.self_attn.q_proj.lora_A
base_model.model.model.layers.0.self_attn.q_proj.lora_A.default
base_model.model.model.layers.0.self_attn.q_proj.lora_B
base_model.model.model.layers.0.self_attn.q_proj.lora_B.default
base_model.model.model.layers.0.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.0.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.0.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.0.self_attn.v_proj.lora_dropout
base_model.model.model.layers.0.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.0.self_attn.v_proj.lora_A
base_model.model.model.layers.0.self_attn.v_proj.lora_A.default
base_model.model.model.layers.0.self_attn.v_proj.lora_B
base_model.model.model.layers.0.self_attn.v_proj.lora_B.default
base_model.model.model.layers.0.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.0.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.0.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.1.self_attn.q_proj.lora_dropout
base_model.model.model.layers.1.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.1.self_attn.q_proj.lora_A
base_model.model.model.layers.1.self_attn.q_proj.lora_A.default
base_model.model.model.layers.1.self_attn.q_proj.lora_B
base_model.model.model.layers.1.self_attn.q_proj.lora_B.default
base_model.model.model.layers.1.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.1.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.1.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.1.self_attn.v_proj.lora_dropout
base_model.model.model.layers.1.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.1.self_attn.v_proj.lora_A
base_model.model.model.layers.1.self_attn.v_proj.lora_A.default
base_model.model.model.layers.1.self_attn.v_proj.lora_B
base_model.model.model.layers.1.self_attn.v_proj.lora_B.default
base_model.model.model.layers.1.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.1.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.1.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.2.self_attn.q_proj.lora_dropout
base_model.model.model.layers.2.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.2.self_attn.q_proj.lora_A
base_model.model.model.layers.2.self_attn.q_proj.lora_A.default
base_model.model.model.layers.2.self_attn.q_proj.lora_B
base_model.model.model.layers.2.self_attn.q_proj.lora_B.default
base_model.model.model.layers.2.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.2.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.2.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.2.self_attn.v_proj.lora_dropout
base_model.model.model.layers.2.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.2.self_attn.v_proj.lora_A
base_model.model.model.layers.2.self_attn.v_proj.lora_A.default
base_model.model.model.layers.2.self_attn.v_proj.lora_B
base_model.model.model.layers.2.self_attn.v_proj.lora_B.default
base_model.model.model.layers.2.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.2.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.2.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.3.self_attn.q_proj.lora_dropout
base_model.model.model.layers.3.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.3.self_attn.q_proj.lora_A
base_model.model.model.layers.3.self_attn.q_proj.lora_A.default
base_model.model.model.layers.3.self_attn.q_proj.lora_B
base_model.model.model.layers.3.self_attn.q_proj.lora_B.default
base_model.model.model.layers.3.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.3.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.3.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.3.self_attn.v_proj.lora_dropout
base_model.model.model.layers.3.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.3.self_attn.v_proj.lora_A
base_model.model.model.layers.3.self_attn.v_proj.lora_A.default
base_model.model.model.layers.3.self_attn.v_proj.lora_B
base_model.model.model.layers.3.self_attn.v_proj.lora_B.default
base_model.model.model.layers.3.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.3.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.3.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.4.self_attn.q_proj.lora_dropout
base_model.model.model.layers.4.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.4.self_attn.q_proj.lora_A
base_model.model.model.layers.4.self_attn.q_proj.lora_A.default
base_model.model.model.layers.4.self_attn.q_proj.lora_B
base_model.model.model.layers.4.self_attn.q_proj.lora_B.default
base_model.model.model.layers.4.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.4.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.4.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.4.self_attn.v_proj.lora_dropout
base_model.model.model.layers.4.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.4.self_attn.v_proj.lora_A
base_model.model.model.layers.4.self_attn.v_proj.lora_A.default
base_model.model.model.layers.4.self_attn.v_proj.lora_B
base_model.model.model.layers.4.self_attn.v_proj.lora_B.default
base_model.model.model.layers.4.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.4.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.4.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.5.self_attn.q_proj.lora_dropout
base_model.model.model.layers.5.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.5.self_attn.q_proj.lora_A
base_model.model.model.layers.5.self_attn.q_proj.lora_A.default
base_model.model.model.layers.5.self_attn.q_proj.lora_B
base_model.model.model.layers.5.self_attn.q_proj.lora_B.default
base_model.model.model.layers.5.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.5.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.5.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.5.self_attn.v_proj.lora_dropout
base_model.model.model.layers.5.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.5.self_attn.v_proj.lora_A
base_model.model.model.layers.5.self_attn.v_proj.lora_A.default
base_model.model.model.layers.5.self_attn.v_proj.lora_B
base_model.model.model.layers.5.self_attn.v_proj.lora_B.default
base_model.model.model.layers.5.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.5.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.5.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.6.self_attn.q_proj.lora_dropout
base_model.model.model.layers.6.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.6.self_attn.q_proj.lora_A
base_model.model.model.layers.6.self_attn.q_proj.lora_A.default
base_model.model.model.layers.6.self_attn.q_proj.lora_B
base_model.model.model.layers.6.self_attn.q_proj.lora_B.default
base_model.model.model.layers.6.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.6.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.6.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.6.self_attn.v_proj.lora_dropout
base_model.model.model.layers.6.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.6.self_attn.v_proj.lora_A
base_model.model.model.layers.6.self_attn.v_proj.lora_A.default
base_model.model.model.layers.6.self_attn.v_proj.lora_B
base_model.model.model.layers.6.self_attn.v_proj.lora_B.default
base_model.model.model.layers.6.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.6.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.6.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.7.self_attn.q_proj.lora_dropout
base_model.model.model.layers.7.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.7.self_attn.q_proj.lora_A
base_model.model.model.layers.7.self_attn.q_proj.lora_A.default
base_model.model.model.layers.7.self_attn.q_proj.lora_B
base_model.model.model.layers.7.self_attn.q_proj.lora_B.default
base_model.model.model.layers.7.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.7.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.7.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.7.self_attn.v_proj.lora_dropout
base_model.model.model.layers.7.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.7.self_attn.v_proj.lora_A
base_model.model.model.layers.7.self_attn.v_proj.lora_A.default
base_model.model.model.layers.7.self_attn.v_proj.lora_B
base_model.model.model.layers.7.self_attn.v_proj.lora_B.default
base_model.model.model.layers.7.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.7.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.7.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.8.self_attn.q_proj.lora_dropout
base_model.model.model.layers.8.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.8.self_attn.q_proj.lora_A
base_model.model.model.layers.8.self_attn.q_proj.lora_A.default
base_model.model.model.layers.8.self_attn.q_proj.lora_B
base_model.model.model.layers.8.self_attn.q_proj.lora_B.default
base_model.model.model.layers.8.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.8.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.8.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.8.self_attn.v_proj.lora_dropout
base_model.model.model.layers.8.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.8.self_attn.v_proj.lora_A
base_model.model.model.layers.8.self_attn.v_proj.lora_A.default
base_model.model.model.layers.8.self_attn.v_proj.lora_B
base_model.model.model.layers.8.self_attn.v_proj.lora_B.default
base_model.model.model.layers.8.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.8.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.8.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.9.self_attn.q_proj.lora_dropout
base_model.model.model.layers.9.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.9.self_attn.q_proj.lora_A
base_model.model.model.layers.9.self_attn.q_proj.lora_A.default
base_model.model.model.layers.9.self_attn.q_proj.lora_B
base_model.model.model.layers.9.self_attn.q_proj.lora_B.default
base_model.model.model.layers.9.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.9.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.9.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.9.self_attn.v_proj.lora_dropout
base_model.model.model.layers.9.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.9.self_attn.v_proj.lora_A
base_model.model.model.layers.9.self_attn.v_proj.lora_A.default
base_model.model.model.layers.9.self_attn.v_proj.lora_B
base_model.model.model.layers.9.self_attn.v_proj.lora_B.default
base_model.model.model.layers.9.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.9.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.9.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.10.self_attn.q_proj.lora_dropout
base_model.model.model.layers.10.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.10.self_attn.q_proj.lora_A
base_model.model.model.layers.10.self_attn.q_proj.lora_A.default
base_model.model.model.layers.10.self_attn.q_proj.lora_B
base_model.model.model.layers.10.self_attn.q_proj.lora_B.default
base_model.model.model.layers.10.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.10.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.10.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.10.self_attn.v_proj.lora_dropout
base_model.model.model.layers.10.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.10.self_attn.v_proj.lora_A
base_model.model.model.layers.10.self_attn.v_proj.lora_A.default
base_model.model.model.layers.10.self_attn.v_proj.lora_B
base_model.model.model.layers.10.self_attn.v_proj.lora_B.default
base_model.model.model.layers.10.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.10.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.10.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.11.self_attn.q_proj.lora_dropout
base_model.model.model.layers.11.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.11.self_attn.q_proj.lora_A
base_model.model.model.layers.11.self_attn.q_proj.lora_A.default
base_model.model.model.layers.11.self_attn.q_proj.lora_B
base_model.model.model.layers.11.self_attn.q_proj.lora_B.default
base_model.model.model.layers.11.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.11.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.11.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.11.self_attn.v_proj.lora_dropout
base_model.model.model.layers.11.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.11.self_attn.v_proj.lora_A
base_model.model.model.layers.11.self_attn.v_proj.lora_A.default
base_model.model.model.layers.11.self_attn.v_proj.lora_B
base_model.model.model.layers.11.self_attn.v_proj.lora_B.default
base_model.model.model.layers.11.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.11.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.11.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.12.self_attn.q_proj.lora_dropout
base_model.model.model.layers.12.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.12.self_attn.q_proj.lora_A
base_model.model.model.layers.12.self_attn.q_proj.lora_A.default
base_model.model.model.layers.12.self_attn.q_proj.lora_B
base_model.model.model.layers.12.self_attn.q_proj.lora_B.default
base_model.model.model.layers.12.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.12.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.12.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.12.self_attn.v_proj.lora_dropout
base_model.model.model.layers.12.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.12.self_attn.v_proj.lora_A
base_model.model.model.layers.12.self_attn.v_proj.lora_A.default
base_model.model.model.layers.12.self_attn.v_proj.lora_B
base_model.model.model.layers.12.self_attn.v_proj.lora_B.default
base_model.model.model.layers.12.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.12.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.12.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.13.self_attn.q_proj.lora_dropout
base_model.model.model.layers.13.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.13.self_attn.q_proj.lora_A
base_model.model.model.layers.13.self_attn.q_proj.lora_A.default
base_model.model.model.layers.13.self_attn.q_proj.lora_B
base_model.model.model.layers.13.self_attn.q_proj.lora_B.default
base_model.model.model.layers.13.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.13.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.13.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.13.self_attn.v_proj.lora_dropout
base_model.model.model.layers.13.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.13.self_attn.v_proj.lora_A
base_model.model.model.layers.13.self_attn.v_proj.lora_A.default
base_model.model.model.layers.13.self_attn.v_proj.lora_B
base_model.model.model.layers.13.self_attn.v_proj.lora_B.default
base_model.model.model.layers.13.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.13.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.13.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.14.self_attn.q_proj.lora_dropout
base_model.model.model.layers.14.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.14.self_attn.q_proj.lora_A
base_model.model.model.layers.14.self_attn.q_proj.lora_A.default
base_model.model.model.layers.14.self_attn.q_proj.lora_B
base_model.model.model.layers.14.self_attn.q_proj.lora_B.default
base_model.model.model.layers.14.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.14.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.14.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.14.self_attn.v_proj.lora_dropout
base_model.model.model.layers.14.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.14.self_attn.v_proj.lora_A
base_model.model.model.layers.14.self_attn.v_proj.lora_A.default
base_model.model.model.layers.14.self_attn.v_proj.lora_B
base_model.model.model.layers.14.self_attn.v_proj.lora_B.default
base_model.model.model.layers.14.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.14.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.14.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.15.self_attn.q_proj.lora_dropout
base_model.model.model.layers.15.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.15.self_attn.q_proj.lora_A
base_model.model.model.layers.15.self_attn.q_proj.lora_A.default
base_model.model.model.layers.15.self_attn.q_proj.lora_B
base_model.model.model.layers.15.self_attn.q_proj.lora_B.default
base_model.model.model.layers.15.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.15.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.15.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.15.self_attn.v_proj.lora_dropout
base_model.model.model.layers.15.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.15.self_attn.v_proj.lora_A
base_model.model.model.layers.15.self_attn.v_proj.lora_A.default
base_model.model.model.layers.15.self_attn.v_proj.lora_B
base_model.model.model.layers.15.self_attn.v_proj.lora_B.default
base_model.model.model.layers.15.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.15.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.15.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.16.self_attn.q_proj.lora_dropout
base_model.model.model.layers.16.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.16.self_attn.q_proj.lora_A
base_model.model.model.layers.16.self_attn.q_proj.lora_A.default
base_model.model.model.layers.16.self_attn.q_proj.lora_B
base_model.model.model.layers.16.self_attn.q_proj.lora_B.default
base_model.model.model.layers.16.self_attn.q_proj.lora_embedding_A
base_model.model.model.layers.16.self_attn.q_proj.lora_embedding_B
base_model.model.model.layers.16.self_attn.q_proj.lora_magnitude_vector
base_model.model.model.layers.16.self_attn.v_proj.lora_dropout
base_model.model.model.layers.16.self_attn.v_proj.lora_dropout.default
base_model.model.model.layers.16.self_attn.v_proj.lora_A
base_model.model.model.layers.16.self_attn.v_proj.lora_A.default
base_model.model.model.layers.16.self_attn.v_proj.lora_B
base_model.model.model.layers.16.self_attn.v_proj.lora_B.default
base_model.model.model.layers.16.self_attn.v_proj.lora_embedding_A
base_model.model.model.layers.16.self_attn.v_proj.lora_embedding_B
base_model.model.model.layers.16.self_attn.v_proj.lora_magnitude_vector
base_model.model.model.layers.17.self_attn.q_proj.lora_dropout
base_model.model.model.layers.17.self_attn.q_proj.lora_dropout.default
base_model.model.model.layers.17.self_attn.q_proj.lora_A
base_model.model.model.layers.17.self_attn.q_proj.lora_A.default
base_model.model.model.layers.17.self_attn.q_proj.lora_B

- 전체 파라미터 수 대비 trainable parameter가 얼마나 작은지
- 왜 full fine-tuning보다 가벼운지
- q_proj, v_proj에만 붙는다는 의미가 무엇인지

### taget_modules 바꿔서 성능 비교

- 비교할 설정
1. ["q_proj", "v_proj"]
2. ["q_proj", "k_proj", "v_proj", "o_proj"]
3. ["gate_proj", "up_proj", "down_proj"]
4. attention + MLP 둘 다

In [20]:
target_module_sets = {
    "attn_small": ["q_proj", "v_proj"],
    "attn_full": ["q_proj", "k_proj", "v_proj", "o_proj"],
    "mlp_only": ["gate_proj", "up_proj", "down_proj"],
    "attn_mlp": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
}

### rank `r` 바꿔보기

- r 작음 → 가볍지만 표현력 제한
- r 큼 → 더 유연하지만 메모리/과적합 증가 가능

In [21]:
lora_alpha = 16
lora_dropout = 0.05
target_modules = ["q_proj", "v_proj"]

In [22]:
# total paras 계산
def count_parameters(model):
    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return total, trainable

total, trainable = count_parameters(lora_model)
print(f"Total params: {total:,}")
print(f"Trainable params: {trainable:,}")
print(f"Trainable ratio: {100 * trainable / total:.4f}%")

Total params: 1,544,803,840
Trainable params: 1,089,536
Trainable ratio: 0.0705%

### LoRA 학습 전/후 hidden state 비교

**모델 내부 표현이 어떻게 바뀌는지**

In [23]:
import torch

text = "Explain quantization in simple terms."
inputs = tokenizer(text, return_tensors="pt").to(lora_model.device)

with torch.no_grad():
    base_outputs = model(**inputs, output_hidden_states=True)
    lora_outputs = lora_model(**inputs, output_hidden_states=True)

base_last = base_outputs.hidden_states[-1]
lora_last = lora_outputs.hidden_states[-1]

diff = torch.norm(base_last - lora_last).item()
print("L2 difference:", diff)

L2 difference: 0.0

### merge 전후 비교

LoRA는 학습 후 base model에 병합할 수 있음.

In [24]:
merged_model = lora_model.merge_and_unload()

In [25]:
#같은 프롬프트로 생성하여 비교
prompt = "Explain overfitting in 3 sentences."

inputs = tokenizer(prompt, return_tensors="pt").to(merged_model.device)

with torch.no_grad():
    output_ids = merged_model.generate(
        **inputs,
        max_new_tokens=80,
        do_sample=False
    )

print(tokenizer.decode(output_ids[0], skip_special_tokens=True))

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Explain overfitting in 3 sentences. Overfitting occurs when a model is too complex and fits the training data perfectly, but fails to generalize well on unseen data due to capturing noise or random fluctuations instead of underlying patterns. It leads to poor performance on new data as it has learned irrelevant details that do not apply outside the dataset. Techniques like regularization, cross-validation, and simpler models can help mitigate overfitting by reducing complexity and improving

## optuna로 LoRA 파라미터 추적

In [1]:
# 라이브러리 설치
!pip install transformers peft datasets accelerate optuna
# GPU 없더라도 아주 작은 모델로는 실습이 가능하지만 속도는 느릴 수 있음.

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cu128)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.48)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft) (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 11.7 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [2]:
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,         #모델에 맞는 토크나이저(텍스트를 숫자로 변환)를 자동으로 선택
    AutoModelForCausalLM,  # GPT/Llama 같은 텍스트 생성용 모델을 자동으로 불러옴
    Trainer,               # 복잡한 학습 루프(루프, 검증, 저장 등)를 추상화 하여 실행
    TrainingArguments,     # 학습률, 배치 크기, 저장 경로 등 하이퍼파라미터를 설정함.
    DataCollatorForLanguageModeling, # 데이터를 모델 입력에 맞게 배치(Batch) 단위로 묶어주는 역할
)
from peft import LoraConfig, get_peft_model, TaskType
#LoraConfig: 저랭크 어텝터 학습을 위한 설정값(rank, alpha 등)을 정의
#get_peft_model: 일반 모델에 LoRA 레이러를 추가하여 효율적 학습이 가능한 모델로 변환
# TaskType: 모델의 작업 유형(ex.Causal LM, seq2seq)을 지정하여 최적의 설정을 도움
import optuna

In [3]:
device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available()
    else "cpu"
)
print("device:", device)

device: cuda

In [4]:
# 작은 instruction 데이터
train_data = [
    {
        "instruction": "QLoRA가 무엇인지 한 문장으로 설명해줘.",
        "response": "QLoRA는 양자화된 대형 언어 모델 위에 LoRA adapter만 학습하는 효율적인 미세조정 방법입니다."
    },
    {
        "instruction": "LoRA가 무엇인지 짧게 설명해줘.",
        "response": "LoRA는 전체 가중치를 모두 업데이트하지 않고 작은 저차원 adapter만 학습하는 파라미터 효율적 미세조정 기법입니다."
    },
    {
        "instruction": "LoRA의 장점을 두 가지 말해줘.",
        "response": "LoRA는 학습해야 하는 파라미터 수를 줄여 메모리를 절약하고, 전체 미세조정보다 더 가볍고 빠르게 실험할 수 있게 해줍니다."
    },
    {
        "instruction": "Transformer를 짧게 설명해줘.",
        "response": "Transformer는 self-attention을 이용해 입력 토큰 간 관계를 학습하는 신경망 구조입니다."
    },
    {
        "instruction": "Attention이 중요한 이유를 설명해줘.",
        "response": "Attention은 현재 토큰과 관련이 큰 입력 부분에 집중하게 하여 문맥 이해를 향상시킵니다."
    },
    {
        "instruction": "Post-Training Quantization을 짧게 설명해줘.",
        "response": "Post-Training Quantization은 학습이 끝난 모델을 낮은 정밀도로 변환하는 방법입니다."
    },
    {
        "instruction": "QAT를 짧게 설명해줘.",
        "response": "QAT는 학습 중에 양자화 오차를 반영해 양자화 후 정확도 저하를 줄이도록 훈련하는 방법입니다."
    },
    {
        "instruction": "LoRA와 full fine-tuning의 차이를 설명해줘.",
        "response": "LoRA는 일부 작은 adapter만 학습하지만 full fine-tuning은 모델의 전체 가중치를 업데이트합니다."
    },
    {
        "instruction": "양자화의 장점을 두 가지 말해줘.",
        "response": "양자화는 모델 크기와 메모리 사용량을 줄이고 더 작은 하드웨어에서도 실행 가능하게 도와줍니다."
    },
    {
        "instruction": "Causal language model이 무엇인지 설명해줘.",
        "response": "Causal language model은 앞의 토큰들을 바탕으로 다음 토큰을 예측하도록 학습된 언어 모델입니다."
    },
]

dataset = Dataset.from_list(train_data)
dataset

Dataset({
    features: ['instruction', 'response'],
    num_rows: 10
})

In [5]:
# 모델 지정
model_id = "Qwen/Qwen2.5-1.5B-Instruct"

In [6]:
tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print("pad_token:", tokenizer.pad_token)
print("eos_token:", tokenizer.eos_token)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

pad_token: <|endoftext|>
eos_token: <|im_end|>

In [7]:
# chat template 적용
def make_chat_text(example):
    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": example["instruction"]},
        {"role": "assistant", "content": example["response"]},
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

dataset = dataset.map(make_chat_text)
print(dataset[0]["text"][:500])

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
QLoRA가 무엇인지 한 문장으로 설명해줘.<|im_end|>
<|im_start|>assistant
QLoRA는 양자화된 대형 언어 모델 위에 LoRA adapter만 학습하는 효율적인 미세조정 방법입니다.<|im_end|>

In [8]:
split_dataset = dataset.train_test_split(test_size=0.2, seed=42)
train_dataset = split_dataset["train"]
eval_dataset = split_dataset["test"]

print("train size:", len(train_dataset))
print("eval size :", len(eval_dataset))

train size: 8
eval size : 2

In [9]:
# 토크나이저 함수

max_length = 256

def tokenize_function(example):
    tokenized = tokenizer(
        example["text"],
        truncation=True,
        max_length=max_length,
        padding="max_length",
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

tokenized_train = train_dataset.map(tokenize_function, remove_columns=train_dataset.column_names)
tokenized_eval = eval_dataset.map(tokenize_function, remove_columns=eval_dataset.column_names)

tokenized_train

Map:   0%|          | 0/8 [00:00<?, ? examples/s]

Map:   0%|          | 0/2 [00:00<?, ? examples/s]

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 8
})

In [10]:
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

In [11]:
# 학습 전/후 함수
def generate_answer(model, question, max_new_tokens=80):
    model.eval()

    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": question},
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(prompt, return_tensors="pt")
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

In [12]:
# 베이스 모델 출력 먼저 확인
base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

print(generate_answer(base_model, "LoRA가 무엇인지 짧게 설명해줘."))

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

system
You are a helpful assistant.
user
LoRA가 무엇인지 짧게 설명해줘.
assistant
LoRA는 LoRaWAN의 약자로, LoRa라는 블루투스 기술을 이용한 장거리 소통 방식입니다. 이 기술은 전력소비가 적고, 장거리에서도 정확하고 안정적인 데이터를 전송할 수 있는 장점이 있습니다. LoRA는 IoT(인공지능) 시

In [ ]:
#LoRA 모델 생성 함수
def build_lora_model(model_id, r, lora_alpha, lora_dropout):
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
    )

    peft_config = LoraConfig(
        r=r,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules="all-linear"
    )

    model = get_peft_model(model, peft_config)
    return model

In [14]:
#Optuna Objetive 함수
def objective(trial):
    r = trial.suggest_categorical("r", [4, 8, 16, 32])
    lora_alpha = trial.suggest_categorical("lora_alpha", [8, 16, 32, 64])
    lora_dropout = trial.suggest_float("lora_dropout", 0.0, 0.2)
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 5e-4, log=True)
    num_train_epochs = trial.suggest_int("num_train_epochs", 2, 4)

    model = build_lora_model(
        model_id=model_id,
        r=r,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout
    )

    output_dir = f"./optuna_trial_{trial.number}"

    training_args = TrainingArguments(
        output_dir=output_dir,
        per_device_train_batch_size=1,
        per_device_eval_batch_size=1,
        gradient_accumulation_steps=4,
        learning_rate=learning_rate,
        num_train_epochs=num_train_epochs,
        eval_strategy="epoch",
        save_strategy="no",
        logging_strategy="epoch",
        report_to="none",
        fp16=torch.cuda.is_available(),
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_eval,
        data_collator=data_collator,
    )

    trainer.train()
    eval_result = trainer.evaluate()

    eval_loss = eval_result["eval_loss"]
    trial.set_user_attr("eval_loss", float(eval_loss))

    del model
    torch.cuda.empty_cache()

    return eval_loss

In [15]:
# Optuna study
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=3)

[I 2026-04-13 06:55:27,621] A new study created in memory with name: no-name-32657efa-e1d4-4d5c-ae17-0c9302f29f21

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

[I 2026-04-13 06:55:51,742] Trial 0 finished with value: 2.6867475509643555 and parameters: {'r': 32, 'lora_alpha': 32, 'lora_dropout': 0.16204392469208578, 'learning_rate': 2.5537990132366477e-05, 'num_train_epochs': 3}. Best is trial 0 with value: 2.6867475509643555.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

[I 2026-04-13 06:56:18,013] Trial 1 finished with value: 1.4084067344665527 and parameters: {'r': 8, 'lora_alpha': 64, 'lora_dropout': 0.17082984539229623, 'learning_rate': 9.954425671668176e-05, 'num_train_epochs': 4}. Best is trial 1 with value: 1.4084067344665527.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

[I 2026-04-13 06:56:44,736] Trial 2 finished with value: 2.9130892753601074 and parameters: {'r': 4, 'lora_alpha': 8, 'lora_dropout': 0.03799752821910932, 'learning_rate': 2.8889050558742164e-05, 'num_train_epochs': 4}. Best is trial 1 with value: 1.4084067344665527.

In [16]:
# 결과 확인
print("Best trial number:", study.best_trial.number)
print("Best value (eval_loss):", study.best_value)
print("Best params:")
for k, v in study.best_trial.params.items():
    print(f"  {k}: {v}")

Best trial number: 1
Best value (eval_loss): 1.4084067344665527
Best params:
  r: 8
  lora_alpha: 64
  lora_dropout: 0.17082984539229623
  learning_rate: 9.954425671668176e-05
  num_train_epochs: 4

In [17]:
# 모든 trail 기록 보기
for t in study.trials:
    print("=" * 60)
    print("trial:", t.number)
    print("params:", t.params)
    print("value :", t.value)
    print("user_attrs:", t.user_attrs)

============================================================
trial: 0
params: {'r': 32, 'lora_alpha': 32, 'lora_dropout': 0.16204392469208578, 'learning_rate': 2.5537990132366477e-05, 'num_train_epochs': 3}
value : 2.6867475509643555
user_attrs: {'eval_loss': 2.6867475509643555}
============================================================
trial: 1
params: {'r': 8, 'lora_alpha': 64, 'lora_dropout': 0.17082984539229623, 'learning_rate': 9.954425671668176e-05, 'num_train_epochs': 4}
value : 1.4084067344665527
user_attrs: {'eval_loss': 1.4084067344665527}
============================================================
trial: 2
params: {'r': 4, 'lora_alpha': 8, 'lora_dropout': 0.03799752821910932, 'learning_rate': 2.8889050558742164e-05, 'num_train_epochs': 4}
value : 2.9130892753601074
user_attrs: {'eval_loss': 2.9130892753601074}

In [18]:
# best parmas로 최종 모델 다시 학습
best_params = study.best_trial.params
best_params

{'r': 8,
 'lora_alpha': 64,
 'lora_dropout': 0.17082984539229623,
 'learning_rate': 9.954425671668176e-05,
 'num_train_epochs': 4}

In [ ]:
final_model = build_lora_model(
    model_id=model_id,
    r=best_params["r"],
    lora_alpha=best_params["lora_alpha"],
    lora_dropout=best_params["lora_dropout"]
)

final_training_args = TrainingArguments(
    output_dir="./final_lora_model",
    overwrite_output_dir=True,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=best_params["learning_rate"],
    num_train_epochs=best_params["num_train_epochs"],
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    report_to="none",
    fp16=torch.cuda.is_available(),
)

final_trainer = Trainer(
    model=final_model,
    args=final_training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_eval,
    data_collator=data_collator,
)

final_trainer.train()

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [ ]:
# 학습 후 출력
print(generate_answer(final_model, "LoRA가 무엇인지 짧게 설명해줘."))
print()
print(generate_answer(final_model, "LoRA와 full fine-tuning의 차이를 설명해줘."))
print()
print(generate_answer(final_model, "양자화의 장점을 두 가지 말해줘."))

In [ ]:
# adapter 저장
save_path = "./best_lora_adapter"
final_model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("saved to:", save_path)

In [ ]:
# 저장한 adapter 다시 불러오기
from peft import PeftModel

base_model_for_infer = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

loaded_model = PeftModel.from_pretrained(base_model_for_infer, save_path)
loaded_model.eval()

print(generate_answer(loaded_model, "LoRA가 무엇인지 짧게 설명해줘."))

# QLoRA (Quantized Low-Rank Adaptation)

사전학습된 대형 언어 모델을 **4-bit 양자화한 상태로 보관**하고, **기본 모델 가중치는 고정(frozen)** 한 채, **작은 LoRA adapter만 학습**하는 미세조정(fine-tuning) 방법.


- **큰 본체 모델**은 매우 가볍게 압축해서 유지하고
- **실제로 학습되는 부분**은 작은 저랭크 보정항만 두는 방식.

---

## 핵심

**메모리 사용량을 크게 줄이면서도, full fine-tuning에 가까운 성능을 얻는 것**이 QLoRA의 핵심.

원 논문에서는 이 방법을 통해 **65B 규모 모델을 단일 48GB GPU에서 미세조정**할 수 있음을 보였다.

---

## 왜 QLoRA가 필요한가?

일반적인 full fine-tuning은 모델의 모든 가중치를 업데이트하므로 다음과 같은 비용이 매우 크다.

- 모델 파라미터 저장 메모리
- gradient 저장 메모리
- optimizer state 저장 메모리

모델 크기가 커질수록 이 세 가지가 모두 급격히 증가.

예를 들어 파라미터 수가 매우 큰 LLM에서는 단순히 모델 가중치만 올리는 것이 아니라,

- forward를 위한 메모리
- backward를 위한 intermediate activation
    - 신경망의 중간층에서 계산되어 잠시 저장되는 출력값
- optimizer가 유지하는 추가 상태값

까지 모두 필요하므로, 실제 학습 비용은 훨씬 더 커짐.

---

## LoRA와 QLoRA의 차이

### LoRA
LoRA는 **학습하는 파라미터 수를 줄이는 방법**.

기존 가중치 전체를 업데이트하지 않고, 작은 저랭크 행렬 $A, B$만 학습하여 보정항을 추가.

$$
W' = W + \Delta W = W + BA
$$

여기서

- $W$: 기존 pretrained weight
- $A, B$: 학습되는 작은 저랭크 행렬
- $\Delta W = BA$: 전체 weight update를 근사하는 보정항

---

### QLoRA
QLoRA는 LoRA의 장점에 더해, **기본 모델 자체를 4-bit로 양자화하여 저장 메모리까지 줄이는 방법**.

- **LoRA**: 학습 파라미터 수를 줄임
- **QLoRA**: 학습 파라미터 수를 줄이면서, 기본 모델 저장도 더 가볍게 함

이라고 볼 수 있다.

---

## 기본 아이디어

QLoRA의 흐름은 다음과 같다.

1. 사전학습 모델 가중치를 **4-bit로 양자화**
2. 양자화된 기본 모델은 **frozen**
3. 역전파는 통과시키되, **업데이트는 LoRA adapter만 수행**
4. 계산 안정성을 위해 일부 연산은 **더 높은 정밀도**로 수행

> 무거운 본체는 작게 압축해서 들고 있고,  
> 실제 학습은 작은 추가 부품만 바꾸는 방식

---

## 수식으로 보는 QLoRA

원래 선형층이 다음과 같다고 하자.

$$
y = Wx
$$

LoRA에서는 여기에 저랭크 보정항을 추가하여

$$
y = \left(W + \frac{\alpha}{r}BA\right)x
$$

로 바꾼다.

- $W \in \mathbb{R}^{d \times k}$: 원래 weight
- $A \in \mathbb{R}^{r \times k}$
- $B \in \mathbb{R}^{d \times r}$
- $r \ll \min(d,k)$: 작은 rank
- $\alpha$: scaling factor

QLoRA에서는 이 $W$를 full precision으로 저장하지 않고, **양자화된 형태**로 유지.

개념적으로는

$$
W \approx \hat{W}_{4bit}
$$

로 보고, 실제 forward에서는

$$
y = \left(\hat{W}_{4bit} + \frac{\alpha}{r}BA\right)x
$$

를 계산.

- $\hat{W}_{4bit}$는 **고정**
- $A, B$만 **학습**

된다는 것.

---

## 양자화는 어떻게 들어가는가?

딥러닝에서 양자화는 실수값을 더 적은 비트 수의 표현으로 근사하는 것.

예를 들어 어떤 실수 가중치 $w$를 정수값 $q$로 바꾸고 다시 근사값 $\hat{w}$로 복원하면,

$$
q = \operatorname{round}\left(\frac{w}{s}\right)
$$

$$
\hat{w} = s q
$$

처럼 생각할 수 있다.

QLoRA에서는 기본 모델 전체를 이런 방식으로 낮은 비트 폭으로 표현.

다만 실제 구현에서는 단순 정수화만이 아니라, **모델 성능 손실을 줄이기 위한 정교한 4-bit 양자화 방식**을 사용.

---

## QLoRA의 핵심 구성 요소

QLoRA를 이해할 때 중요한 구성 요소는 다음과 같다.

### 1. 4-bit NormalFloat (NF4)
QLoRA는 보통 **NF4**라는 4-bit 데이터 타입을 사용한다.

NF4는 일반적인 균등 양자화보다, **정규분포 형태의 weight 분포를 더 잘 반영하도록 설계된 4-bit 표현 방식**.

LLM의 가중치는 대체로 특정 분포를 가지므로, 이런 특성을 활용하면 단순 INT4보다 더 좋은 근사를 얻을 수 있다.

---

### 2. Double Quantization
양자화에서는 scale 같은 추가 정보도 저장해야 한다.

QLoRA는 이 scale 값들조차 다시 양자화하여 **추가 메모리까지 더 절약**.


- weight를 양자화하고
- 그 양자화에 필요한 보조 파라미터도 다시 압축하는 방식이다.

이 때문에 “4-bit로 줄였다”는 것이 단순히 weight 값만 줄인 것이 아니라, 전체 저장 구조를 매우 효율적으로 구성한 것에 가깝다.

---

### 3. Paged Optimizer
대형 모델 학습에서는 optimizer state와 순간적인 메모리 스파이크도 부담이 됨.  
QLoRA는 이런 문제를 줄이기 위해 **paged optimizer** 개념을 사용.

이는 메모리 사용량이 갑자기 튀는 상황을 완화하여, 제한된 GPU 메모리 안에서 더 안정적으로 학습하도록 돕는다.

---

## 왜 4-bit인데도 학습이 가능한가?

여기서 자주 생기는 오해는 다음과 같다.

> “기본 모델이 4-bit면 gradient 계산도 잘 안 되는 것 아닌가?”

핵심은 **기본 모델을 직접 업데이트하지 않는다는 점**.

QLoRA에서는

- 양자화된 base model은 forward 계산에 사용되고
- backward는 그 경로를 따라 흐르지만
- 실제 파라미터 업데이트는 LoRA adapter에만 적용된다.

학습의 자유도를 작게 제한하는 대신 메모리를 크게 절약하는 것이다.

---

## Full Fine-Tuning, LoRA, QLoRA 비교

| 방법 | 기본 모델 업데이트 | 추가 파라미터 | 기본 모델 저장 방식 | 메모리 사용 |
|------|-------------------|----------------|----------------------|-------------|
| Full Fine-Tuning | 전체 업데이트 | 없음 | 보통 FP16/BF16/FP32 | 가장 큼 |
| LoRA | 본체 고정, adapter만 업데이트 | 작음 | 보통 FP16/BF16 | 중간 |
| QLoRA | 본체 고정, adapter만 업데이트 | 작음 | 4-bit 양자화 | 가장 작음 |

---

## QLoRA의 장점

### 1. 매우 큰 메모리 절감
기본 모델을 4-bit로 저장하므로, pretrained model 자체의 메모리 부담이 크게 줄어듬.

### 2. 작은 GPU에서도 대형 모델 미세조정 가능
기존에는 여러 GPU나 매우 큰 GPU 메모리가 필요했던 설정을, 더 제한된 환경에서도 시도할 수 있다.

### 3. LoRA의 효율성 유지
학습 파라미터 수가 작아서 optimizer state와 gradient 메모리도 줄어듬.

### 4. 성능 대비 효율이 좋음
full fine-tuning보다 훨씬 가볍지만, 적절한 설정에서는 매우 경쟁력 있는 성능을 낼 수 있다.

---

## QLoRA의 한계

### 1. Full Fine-Tuning을 완전히 대체하는 것은 아님
모든 상황에서 full fine-tuning과 완전히 동일한 성능을 내는 것은 아니다.

특히 매우 큰 도메인 변화나 복잡한 적응이 필요할 때는 한계가 있을 수 있다.

### 2. 양자화 오차가 존재
기본 모델이 4-bit 근사값으로 저장되므로, 원래 full precision 가중치와는 차이가 있다.

### 3. 학습 가능한 부분이 제한됨
업데이트가 LoRA adapter에만 일어나므로, 모델 전체를 자유롭게 수정하는 것보다 표현력이 제한될 수 있다.

### 4. 구현 세부사항에 영향을 많이 받음
어떤 layer에 adapter를 붙이는지, rank를 얼마로 둘지, 학습률을 어떻게 설정하는지에 따라 결과가 꽤 달라질 수 있다.

---

## QLoRA에서 자주 조절하는 하이퍼파라미터

### 1. rank $r$
LoRA 보정항의 크기를 결정한다.

$$
\Delta W = BA
$$

에서 $A, B$의 중간 차원인 $r$이 클수록 더 풍부한 보정이 가능하지만, 학습 파라미터 수와 메모리도 증가.

---

### 2. LoRA alpha
보정항의 크기를 조절하는 스케일 파라미터.

$$
W' = W + \frac{\alpha}{r}BA
$$

에서 $\alpha$가 너무 작으면 adaptation이 약하고, 너무 크면 불안정할 수 있다.

---

### 3. target modules
Transformer의 어떤 선형층에 LoRA를 붙일지 정한다.

보통 다음과 같은 attention projection에 많이 적용.

- `q_proj`
- `k_proj`
- `v_proj`
- `o_proj`

경우에 따라 MLP layer까지 포함하기도 한다.

---

### 4. 학습률, batch size, sequence length
QLoRA도 결국 미세조정이므로, 일반적인 fine-tuning 설정의 영향을 크게 받는다.  
특히 sequence length가 길어지면 activation memory가 다시 커질 수 있다.

---

## Transformer에서 QLoRA가 붙는 위치

Transformer의 attention에서 보통

$$
Q = W_Q x, \quad K = W_K x, \quad V = W_V x
$$

처럼 projection을 계산.

QLoRA에서는 예를 들어 $W_Q$, $W_V$에 대해

$$
W_Q' = \hat{W}_{Q,4bit} + \frac{\alpha}{r}B_QA_Q
$$

$$
W_V' = \hat{W}_{V,4bit} + \frac{\alpha}{r}B_VA_V
$$

처럼 두고, base weight는 양자화된 채로 고정하고 adapter만 학습한다.

---

- **기본 모델**: 아주 크고 무거운 기계
- **양자화**: 그 기계를 가능한 한 가볍게 압축해서 보관
- **LoRA adapter**: 기계 전체를 뜯어고치지 않고, 작은 조절 장치만 추가
- **학습**: 그 작은 조절 장치만 조정
  
**큰 본체는 그대로 두고, 작은 보정 장치만 훈련해서 목적에 맞게 적응시키는 방식**.

---

## 언제 QLoRA를 쓰면 좋은가?

QLoRA는 다음과 같은 상황에서 특히 유용하다.

- GPU 메모리가 제한적일 때
- 큰 LLM을 직접 full fine-tuning하기 어려울 때
- 특정 태스크나 도메인에 빠르게 적응시키고 싶을 때
- 여러 adapter를 따로 관리하며 실험하고 싶을 때

예를 들어,

- 의료 문서 요약
- 법률 문서 질의응답
- 고객지원 챗봇
- 특정 스타일 답변 생성

같이 특정 목적에 맞는 모델 적응에 자주 활용.

In [ ]:
!pip -q install -U transformers accelerate peft trl bitsandbytes datasets pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 30.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 678.0/678.0 kB 16.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 19.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 9.9 MB/s eta 0:00:00

In [ ]:
import torch

print("torch version:", torch.__version__)
print("cuda available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("gpu:", torch.cuda.get_device_name(0))
else:
    print("cpu")

torch version: 2.10.0+cu128
cuda available: True
gpu: Tesla T4

In [ ]:
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)
from trl import SFTTrainer

In [ ]:
# 아주 작은 실습 데이터
train_data = [
    {
        "instruction": "QLoRA가 무엇인지 한 문장으로 설명해줘.",
        "response": "QLoRA는 4비트로 양자화한 대형 언어 모델 위에 LoRA adapter만 학습하는 효율적인 미세조정 방법입니다."
    },
    {
        "instruction": "LoRA가 full fine-tuning보다 가벼운 이유를 설명해줘.",
        "response": "LoRA는 전체 가중치를 모두 업데이트하지 않고 작은 저차원 adapter만 학습하기 때문에 메모리와 계산량이 크게 줄어듭니다."
    },
    {
        "instruction": "양자화의 장점을 두 가지 말해줘.",
        "response": "양자화는 모델 메모리 사용량을 줄이고 더 작은 GPU에서도 모델을 실행하거나 학습할 수 있게 도와줍니다."
    },
    {
        "instruction": "Transformer를 아주 짧게 설명해줘.",
        "response": "Transformer는 self-attention을 이용해 문맥을 반영하며 토큰 간 관계를 학습하는 신경망 구조입니다."
    },
    {
        "instruction": "Attention이 중요한 이유를 설명해줘.",
        "response": "Attention은 입력 전체 중에서 현재 토큰과 관련이 큰 부분에 집중하게 해 주어 문맥 이해를 향상시킵니다."
    },
    {
        "instruction": "Post-Training Quantization을 짧게 설명해줘.",
        "response": "Post-Training Quantization은 학습이 끝난 모델을 나중에 낮은 정밀도로 변환하는 방법입니다."
    },
    {
        "instruction": "QAT를 짧게 설명해줘.",
        "response": "QAT는 학습 중에 양자화 오차를 반영하여 양자화 후 정확도 저하를 줄이도록 훈련하는 방법입니다."
    },
    {
        "instruction": "QLoRA의 핵심 아이디어를 설명해줘.",
        "response": "QLoRA의 핵심은 양자화된 본체 가중치는 고정하고 작은 LoRA 모듈만 학습해서 메모리를 절약하는 것입니다."
    },
]

dataset = Dataset.from_list(train_data)
dataset

Dataset({
    features: ['instruction', 'response'],
    num_rows: 8
})

In [ ]:
# 모델 지정
model_id = "Qwen/Qwen2.5-1.5B-Instruct"

In [ ]:
# 토크나이저 로드
tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print("pad_token:", tokenizer.pad_token)
print("eos_token:", tokenizer.eos_token)

pad_token: <|endoftext|>
eos_token: <|im_end|>

In [ ]:
#chat template 형태로 학습용 텍스트 만들기
## instruct 모델은 대화 형식이 잘 맞음

def make_chat_text(example):
    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": example["instruction"]},
        {"role": "assistant", "content": example["response"]},
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

dataset = dataset.map(make_chat_text)
dataset[0]["text"][:500]

Map:   0%|          | 0/8 [00:00<?, ? examples/s]

'<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\nQLoRA가 무엇인지 한 문장으로 설명해줘.<|im_end|>\n<|im_start|>assistant\nQLoRA는 4비트로 양자화한 대형 언어 모델 위에 LoRA adapter만 학습하는 효율적인 미세조정 방법입니다.<|im_end|>\n'

- bit 양자화 설정
    - load_in_4bit=True
    - bnb_4bit_quant_type="nf4"
    - bnb_4bit_use_double_quant=True
    - bnb_4bit_compute_dtype=torch.bfloat16

    
조합을 제시. 또한 NF4는 4-bit 학습용으로 권장

In [ ]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16
)

In [ ]:
# 모델 로드
## 학습시에는 device_map="auto"를 주지 않음. /  추론용이기 때문에

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    trust_remote_code=True
)

model.config.use_cache = False

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [ ]:
# k-bit training
# 양자화된 모델을 학습 전에 prepare_model_for_kbit_training()으로 전처리하라고 안내
model = prepare_model_for_kbit_training(model)

In [ ]:
# LoRA 설정
# PEFT 문서 예시는 특정 projection 레이어를 지정하지만, 실습에서는 더 편하게 all-linear를 씀.
peft_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules="all-linear"
)

In [ ]:
# LoRA 모델 만들기
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

trainable params: 9,232,384 || all params: 1,552,946,688 || trainable%: 0.5945

**전체 모델이 아니라 일부 adapter만 학습**

In [ ]:
# 학습전 출력 함수
def generate_answer(question, max_new_tokens=80):
    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": question},
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return decoded

test_question = "QLoRA가 무엇인지 한 문장으로 설명해줘."
print(generate_answer(test_question))

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

system
You are a helpful assistant.
user
QLoRA가 무엇인지 한 문장으로 설명해줘.
assistant
QLoRA는 Quasi-Latent Representation Autoencoder의 약자로, 머신러닝 및 인공지능 분야에서 주로 사용되는 개념입니다.

In [ ]:
# 학습 설정
training_args = TrainingArguments(
    output_dir="./qlora-output",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    learning_rate=2e-4,
    logging_steps=1,
    save_strategy="no",
    report_to="none",
    fp16=False,
    bf16=torch.cuda.is_available(),
    optim="paged_adamw_8bit"
)

In [ ]:
# Trainer 만들기

# 기존 어댑터를 베이스 모델에 완전히 통합
model = model.merge_and_unload()


trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    args=training_args,
    peft_config=peft_config,
)

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/bnb.py:397: UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Adding EOS to train dataset:   0%|          | 0/8 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/8 [00:00<?, ? examples/s]

In [ ]:
# 학습 실행
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

TrainOutput(global_step=6, training_loss=2.809779405593872, metrics={'train_runtime': 27.6106, 'train_samples_per_second': 0.869, 'train_steps_per_second': 0.217, 'total_flos': 13728837408768.0, 'train_loss': 2.809779405593872})

In [ ]:
#학습 후 다시 비교

print(generate_answer("QLoRA가 무엇인지 한 문장으로 설명해줘."))
print()
print(generate_answer("양자화의 장점을 두 가지 말해줘."))

`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
Caching is incompatible with gradient checkpointing in Qwen2DecoderLayer. Setting `past_key_values=None`.
/usr/local/lib/python3.12/dist-packages/torch/utils/checkpoint.py:232: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  check_backward_validity(args)

system
You are a helpful assistant.
user
QLoRA가 무엇인지 한 문장으로 설명해줘.
assistant
QL Ly下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小

system
You are a helpful assistant.
user
양자화의 장점을 두 가지 말해줘.
assistant
양역 Ly下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小下面是小

In [ ]:
# adapter 저장
## QLoRA에서는 보통 전체 모델이 아니라 LoRA Adapter만 저장
save_path = "./qwen2.5-1.5b-qlora-adapter"
trainer.model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("saved to:", save_path)

saved to: ./qwen2.5-1.5b-qlora-adapter

In [ ]:
#저장된 adapter 불러오기
from peft import PeftModel

base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    trust_remote_code=True
)

loaded_model = PeftModel.from_pretrained(base_model, save_path)
loaded_model.eval()

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen2ForCausalLM(
      (model): Qwen2Model(
        (embed_tokens): Embedding(151936, 1536)
        (layers): ModuleList(
          (0-27): 28 x Qwen2DecoderLayer(
            (self_attn): Qwen2Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=1536, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=1536, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=256, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=256, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=256, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=256, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=1536, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=1536, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
            )
            (mlp): Qwen2MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=8960, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=8960, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=8960, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=8960, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=8960, out_features=1536, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=8960, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=1536, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
            (post_attention_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
          )
        )
        (norm): Qwen2RMSNorm((1536,), eps=1e-06)
        (rotary_emb): Qwen2RotaryEmbedding()
      )
      (lm_head): Linear(in_features=1536, out_features=151936, bias=False)
    )
  )
)

- mac book M4 pro silon

In [ ]:
!pip install -U "mlx-lm[train]" datasets

Requirement already satisfied: datasets in /opt/anaconda3/lib/python3.11/site-packages (4.8.4)
Requirement already satisfied: mlx-lm[train] in /opt/anaconda3/lib/python3.11/site-packages (0.31.2)
Requirement already satisfied: mlx>=0.30.4 in /opt/anaconda3/lib/python3.11/site-packages (from mlx-lm[train]) (0.31.1)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.11/site-packages (from mlx-lm[train]) (1.24.4)
Requirement already satisfied: transformers>=5.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from mlx-lm[train]) (5.5.0)
Requirement already satisfied: sentencepiece in /opt/anaconda3/lib/python3.11/site-packages (from mlx-lm[train]) (0.2.1)
Requirement already satisfied: protobuf in /opt/anaconda3/lib/python3.11/site-packages (from mlx-lm[train]) (3.20.3)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.11/site-packages (from mlx-lm[train]) (6.0.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.11/site-packages (from mlx-lm[train]) (3.1.3)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.11/site-packages (from mlx-lm[train]) (4.67.3)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (3.13.1)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (1.5.3)
Requirement already satisfied: requests>=2.32.2 in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (2.33.0)
Requirement already satisfied: httpx<1.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /opt/anaconda3/lib/python3.11/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2023.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (1.9.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.11/site-packages (from datasets) (23.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/anaconda3/lib/python3.11/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.9.3)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.11/site-packages (from httpx<1.0.0->datasets) (4.2.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.11/site-packages (from httpx<1.0.0->datasets) (2024.2.2)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.11/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.11/site-packages (from httpx<1.0.0->datasets) (3.4)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.11/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /opt/anaconda3/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer in /opt/anaconda3/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/anaconda3/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: mlx-metal==0.31.1 in /opt/anaconda3/lib/python3.11/site-packages (from mlx>=0.30.4->mlx-lm[train]) (0.31.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.11/site-packages (from requests>=2.32.2->datasets) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/lib/python3.11/site-packages (from requests>=2.32.2->datasets) (2.0.7)
Requirement already satisfied: regex>=2025.10.22 in /opt/anaconda3/lib/python3.11/site-packages (from transformers>=5.0.0->mlx-lm[train]) (2026.3.32)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /opt/anaconda3/lib/python3.11/site-packages (from transformers>=5.0.0->mlx-lm[train]) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /opt/anaconda3/lib/python3.11/site-packages (from transformers>=5.0.0->mlx-lm[train]) (0.7.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.11/site-packages (from jinja2->mlx-lm[train]) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas->datasets) (2023.3.post1)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.9.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.11/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /opt/anaconda3/lib/python3.11/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/lib/python3.11/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /opt/anaconda3/lib/python3.11/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (13.3.5)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/anaconda3/lib/python3.11/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /opt/anaconda3/lib/python3.11/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.11/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.11/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.0)

In [ ]:
# 작은 예제
import os, json

os.makedirs("toy_lora_data", exist_ok=True)

train_samples = [
    {
        "messages": [
            {"role": "user", "content": "LoRA를 쉽게 설명해줘."},
            {"role": "assistant", "content": "LoRA는 큰 모델 전체를 다시 학습하지 않고, 작은 추가 행렬만 학습해서 모델을 빠르게 적응시키는 방법이야."}
        ]
    },
    {
        "messages": [
            {"role": "user", "content": "QLoRA를 쉽게 설명해줘."},
            {"role": "assistant", "content": "QLoRA는 모델 본체를 양자화해서 메모리를 줄이고, 그 위에 LoRA adapter만 학습하는 방법이야."}
        ]
    },
    {
        "messages": [
            {"role": "user", "content": "Transformer의 attention을 한 줄로 설명해줘."},
            {"role": "assistant", "content": "Attention은 각 토큰이 다른 토큰들을 얼마나 참고할지 가중치를 계산하는 방식이야."}
        ]
    },
    {
        "messages": [
            {"role": "user", "content": "미세조정이 뭐야?"},
            {"role": "assistant", "content": "미세조정은 사전학습된 모델을 특정 데이터와 목적에 맞게 추가 학습하는 과정이야."}
        ]
    },
    {
        "messages": [
            {"role": "user", "content": "양자화의 장점을 짧게 말해줘."},
            {"role": "assistant", "content": "양자화는 모델 메모리 사용량과 계산 비용을 줄여서 더 작은 장치에서도 실행하기 쉽게 해줘."}
        ]
    }
]

valid_samples = [
    {
        "messages": [
            {"role": "user", "content": "LoRA와 full fine-tuning 차이를 설명해줘."},
            {"role": "assistant", "content": "Full fine-tuning은 모든 가중치를 업데이트하지만, LoRA는 작은 adapter만 학습해서 훨씬 가볍다."}
        ]
    }
]

test_samples = [
    {
        "messages": [
            {"role": "user", "content": "QLoRA가 왜 메모리를 아끼는지 설명해줘."},
            {"role": "assistant", "content": "모델 본체를 양자화해 저장 비용을 줄이고, 학습 대상도 작은 LoRA 파라미터만 남기기 때문이야."}
        ]
    }
]

for name, data in [("train", train_samples), ("valid", valid_samples), ("test", test_samples)]:
    with open(f"toy_lora_data/{name}.jsonl", "w", encoding="utf-8") as f:
        for row in data:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

print("완료")

#MLX-LM의 공식 LoRA 문서는 train.jsonl, valid.jsonl, test.jsonl 형태와 messages 기반의 chat 포맷을 지원

완료

In [ ]:
# 가벼운 Instruct 모델
from mlx_lm import load, generate

MODEL_NAME = "mlx-community/Qwen2.5-1.5B-Instruct-4bit"

model, tokenizer = load(MODEL_NAME)

prompt = "### 질문: LoRA를 쉽게 설명해줘.\n### 답변:"

response = generate(
    model,
    tokenizer,
    prompt=prompt,
    max_tokens=80
)

print(response)

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

LoRA는 LoRaWAN의 브랜드 이름입니다. LoRaWAN은 LoRa의 확장된 버전으로, 2015년에 출시된 100kbps의 소프트웨어 브라우저를 통해 100kbps의 속도를 제공합니다. LoRaWAN

In [ ]:
#QLoRA 학습 진행

!mlx_lm.lora \
    --model mlx-community/Qwen2.5-1.5B-Instruct-4bit \
    --train \
    --data toy_lora_data \
    --adapter-path toy_adapters \
    --batch-size 1 \
    --iters 120 \
    --steps-per-report 10 \
    --steps-per-eval 20 \
    --save-every 20 \
    --learning-rate 1e-4
#quantized model을 --model로 주면 regular LoRA가 아니라 QLoRA로 동작

Loading pretrained model
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 9 files: 100%|█████████████████████████| 9/9 [00:00<00:00, 9815.06it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading datasets
Training
Trainable parameters: 0.342% (5.276M/1543.714M)
Starting training..., iters: 120
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00, 11.48it/s]
Iter 1: Val loss 3.862, Val took 0.089s
Iter 10: Train loss 1.320, Learning Rate 1.000e-04, It/sec 7.320, Tokens/sec 551.901, Trained Tokens 754, Peak mem 1.414 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00, 14.19it/s]
Iter 20: Val loss 2.009, Val took 0.072s
Iter 20: Train loss 0.176, Learning Rate 1.000e-04, It/sec 8.085, Tokens/sec 609.589, Trained Tokens 1508, Peak mem 1.414 GB
Iter 20: Saved adapter weights to toy_adapters/adapters.safetensors and toy_adapters/0000020_adapters.safetensors.
Iter 30: Train loss 0.138, Learning Rate 1.000e-04, It/sec 7.531, Tokens/sec 567.863, Trained Tokens 2262, Peak mem 1.435 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00, 14.15it/s]
Iter 40: Val loss 2.294, Val took 0.073s
Iter 40: Train loss 0.051, Learning Rate 1.000e-04, It/sec 7.974, Tokens/sec 601.221, Trained Tokens 3016, Peak mem 1.435 GB
Iter 40: Saved adapter weights to toy_adapters/adapters.safetensors and toy_adapters/0000040_adapters.safetensors.
Iter 50: Train loss 0.037, Learning Rate 1.000e-04, It/sec 8.034, Tokens/sec 605.782, Trained Tokens 3770, Peak mem 1.435 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00, 14.06it/s]
Iter 60: Val loss 2.495, Val took 0.074s
Iter 60: Train loss 0.030, Learning Rate 1.000e-04, It/sec 7.999, Tokens/sec 603.160, Trained Tokens 4524, Peak mem 1.435 GB
Iter 60: Saved adapter weights to toy_adapters/adapters.safetensors and toy_adapters/0000060_adapters.safetensors.
Iter 70: Train loss 0.026, Learning Rate 1.000e-04, It/sec 8.018, Tokens/sec 604.580, Trained Tokens 5278, Peak mem 1.435 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00, 12.31it/s]
Iter 80: Val loss 2.603, Val took 0.083s
Iter 80: Train loss 0.026, Learning Rate 1.000e-04, It/sec 7.439, Tokens/sec 560.885, Trained Tokens 6032, Peak mem 1.435 GB
Iter 80: Saved adapter weights to toy_adapters/adapters.safetensors and toy_adapters/0000080_adapters.safetensors.
Iter 90: Train loss 0.026, Learning Rate 1.000e-04, It/sec 7.647, Tokens/sec 576.580, Trained Tokens 6786, Peak mem 1.435 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00, 13.38it/s]
Iter 100: Val loss 2.637, Val took 0.077s
Iter 100: Train loss 0.027, Learning Rate 1.000e-04, It/sec 7.544, Tokens/sec 568.837, Trained Tokens 7540, Peak mem 1.435 GB
Iter 100: Saved adapter weights to toy_adapters/adapters.safetensors and toy_adapters/0000100_adapters.safetensors.
Iter 110: Train loss 0.025, Learning Rate 1.000e-04, It/sec 7.425, Tokens/sec 559.849, Trained Tokens 8294, Peak mem 1.435 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00, 13.74it/s]
Iter 120: Val loss 2.629, Val took 0.076s
Iter 120: Train loss 0.026, Learning Rate 1.000e-04, It/sec 7.495, Tokens/sec 565.145, Trained Tokens 9048, Peak mem 1.435 GB
Iter 120: Saved adapter weights to toy_adapters/adapters.safetensors and toy_adapters/0000120_adapters.safetensors.
Saved final weights to toy_adapters/adapters.safetensors.

In [ ]:
# Adapter 붙여서 생성
!mlx_lm.generate \
    --model mlx-community/Qwen2.5-1.5B-Instruct-4bit \
    --adapter-path toy_adapters \
    --prompt "### 질문: QLoRA를 쉽게 설명해줘.\n### 답변:"

Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 9 files: 100%|████████████████████████| 9/9 [00:00<00:00, 14728.34it/s]
Download complete: : 0.00B [00:00, ?B/s]
==========
LoRA는 큰 모델 전체를 다시 학습하지 않고, 작은 추가 행렬만 학습해서 모델을 빠르게 적응시키는 방법이야.
==========
Prompt: 44 tokens, 517.955 tokens-per-sec
Generation: 41 tokens, 118.460 tokens-per-sec
Peak memory: 1.033 GB

In [ ]:
# 베이스 모델 VS QLoRA 모델

test_prompt = "### 질문: QLoRA를 쉽게 설명해줘.\n### 답변:"

print("===== Base Model =====")
base_out = generate(
    model,
    tokenizer,
    prompt=test_prompt,
    max_tokens=80
)
print(base_out)

print("\n===== QLoRA Model =====")
!mlx_lm.generate \
    --model mlx-community/Qwen2.5-1.5B-Instruct-4bit \
    --adapter-path toy_adapters \
    --prompt "### 질문: QLoRA를 쉽게 설명해줘.\n### 답변:"

===== Base Model =====
QLoRA는 Qwen의 레이아웃을 따르는 새로운 모델입니다. 이는 Qwen의 4개의 모델을 2개로 나누어 2개의 모델을 2개의 모델로 나누어 2개의 모델을 2개의 모델로 나누어 2개의 모

===== QLoRA Model =====
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 9 files: 100%|████████████████████████| 9/9 [00:00<00:00, 14896.90it/s]
Download complete: : 0.00B [00:00, ?B/s]
==========
LoRA는 큰 모델 전체를 다시 학습하지 않고, 작은 추가 행렬만 학습해서 모델을 빠르게 적응시키는 방법이야.
==========
Prompt: 44 tokens, 541.591 tokens-per-sec
Generation: 41 tokens, 107.038 tokens-per-sec
Peak memory: 1.034 GB

- Qwen3.5-4B

In [ ]:
from mlx_lm import load, generate

MODEL_NAME = "mlx-community/Qwen3.5-4B-MLX-4bit"

model, tokenizer = load(MODEL_NAME)
print("모델 로드 완료")

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]

모델 로드 완료

In [ ]:
prompt = "### 질문: LoRA를 쉽게 설명해줘.\n### 답변:"

response = generate(
    model,
    tokenizer,
    prompt=prompt,
    max_tokens=120
)

print(response)

LoRA (Low-Rank Adaptation) 는 대규모 언어 모델 (LLM) 을 학습할 때, 전체 모델의 모든 파라미터를 업데이트하지 않고, **작은 하위 공간 (subspace) 에만 학습을 수행**하는 기술입니다. 이를 통해 **학습 효율을 높이고, 데이터 효율성을 개선**할 수 있습니다.

---

### **1. LoRA 의 핵심 개념**
#### **1.1. 전체 모델 학습 vs LoRA**
- **전체 모델 학습**: LLM 의 모든 파라미터를 업데이트해야 합니다.
-

In [ ]:
#chat template 방식

messages = [
    {"role": "system", "content": "You are a clear and patient teacher."},
    {"role": "user", "content": "LoRA를 쉽게 설명해줘."}
]

prompt = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True
)

response = generate(
    model,
    tokenizer,
    prompt=prompt,
    max_tokens=120
)

print(response)

Thinking Process:

1.  **Analyze the Request:**
    *   **Topic:** LoRA (Low-Rank Adaptation).
    *   **Goal:** Explain it simply (쉽게 설명해줘).
    *   **Role:** Clear and patient teacher (명확하고 인내심 있는 선생님).
    *   **Language:** Korean.

2.  **Determine the Core Concept:**
    *   What is LoRA? It's a technique for fine-tuning large language models (LLMs) efficiently.
    *   Key analogy: Adding

In [ ]:
#두 방식 비교
plain_prompt = "### 질문: QLoRA를 쉽게 설명해줘.\n### 답변:"

plain_out = generate(
    model,
    tokenizer,
    prompt=plain_prompt,
    max_tokens=120
)

messages = [
    {"role": "system", "content": "You are a clear and patient teacher."},
    {"role": "user", "content": "QLoRA를 쉽게 설명해줘."}
]

chat_prompt = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True
)

chat_out = generate(
    model,
    tokenizer,
    prompt=chat_prompt,
    max_tokens=120
)

print("===== Plain Prompt =====")
print(plain_out)

print("\n===== Chat Template =====")
print(chat_out)

===== Plain Prompt =====
QLoRA는 양자 컴퓨팅의 특정 알고리즘을 의미합니다. 양자 컴퓨터는 고전 컴퓨터와 달리 큐비트 (qubit) 를 사용하여 정보를 처리하며, QLoRA 는 이러한 양자 상태를 활용하여 복잡한 문제를 해결하는 데 사용됩니다. QLoRA 는 양자 머신러닝의 한 분야로, 양자 데이터의 처리와 양자 알고리즘의 최적화를 통해 더 빠른 계산과 더 정확한 결과를 제공합니다.
### 질문: QLoRA 와 LoRA 의 차이점은 무엇인가요?
### 답변: QLoRA 와 LoRA

===== Chat Template =====
Thinking Process:

1.  **Analyze the Request:**
    *   **Topic:** QLoRA (Quantized Low-Rank Adaptation).
    *   **Task:** Explain it simply (쉽게 설명해줘).
    *   **Role:** Clear and patient teacher (명확하고 인내심 있는 선생님).
    *   **Language:** Korean.

2.  **Determine the Core Concept:**
    *   What is QLoRA? It's a technique to fine-tune large language models (LLMs) efficiently.
    *

In [ ]:
#QLoRA는 대규모 학습이 아니라, 보통 응답 형식과 스타일을 특정 방향으로 적응

import os, json

os.makedirs("qwen35_qlora_data", exist_ok=True)

train_samples = [
    {
        "messages": [
            {"role": "user", "content": "LoRA를 쉽게 설명해줘."},
            {"role": "assistant", "content":
             "정의: LoRA는 큰 모델 전체를 다시 학습하지 않고 작은 저랭크 adapter만 학습하는 방법이다.\n"
             "핵심: 전체 가중치를 모두 업데이트하지 않아서 메모리와 계산량을 줄일 수 있다.\n"
             "예시: 원래 모델은 그대로 두고, 특정 태스크에 맞는 작은 보정만 추가하는 방식이다.\n"
             "한줄요약: 적은 비용으로 미세조정을 가능하게 하는 기법이다."}
        ]
    },
    {
        "messages": [
            {"role": "user", "content": "QLoRA를 쉽게 설명해줘."},
            {"role": "assistant", "content":
             "정의: QLoRA는 양자화된 베이스 모델 위에서 LoRA adapter만 학습하는 미세조정 방법이다.\n"
             "핵심: 베이스 모델을 4-bit처럼 더 가볍게 저장하여 메모리를 절약한다.\n"
             "예시: 큰 모델 본체는 고정하고, 작은 adapter만 학습한다.\n"
             "한줄요약: LoRA를 더 적은 메모리로 수행하게 해주는 방법이다."}
        ]
    },
    {
        "messages": [
            {"role": "user", "content": "Attention을 쉽게 설명해줘."},
            {"role": "assistant", "content":
             "정의: Attention은 각 토큰이 다른 토큰을 얼마나 참고할지 계산하는 메커니즘이다.\n"
             "핵심: 문맥상 중요한 단어에 더 큰 가중치를 줄 수 있다.\n"
             "예시: 문장 안에서 어떤 단어가 현재 단어 해석에 중요한지 수치적으로 반영한다.\n"
             "한줄요약: 어떤 정보에 집중할지를 정하는 계산이다."}
        ]
    },
    {
        "messages": [
            {"role": "user", "content": "양자화의 장점을 설명해줘."},
            {"role": "assistant", "content":
             "정의: 양자화는 모델 수치 표현의 비트 수를 줄여 모델을 더 가볍게 만드는 기법이다.\n"
             "핵심: 메모리 사용량과 추론 비용을 줄일 수 있다.\n"
             "예시: float16 대신 4-bit 수준으로 가중치를 저장하는 식이다.\n"
             "한줄요약: 모델을 작고 효율적으로 만드는 방법이다."}
        ]
    }
]

valid_samples = [
    {
        "messages": [
            {"role": "user", "content": "미세조정을 설명해줘."},
            {"role": "assistant", "content":
             "정의: 미세조정은 사전학습된 모델을 특정 목적과 데이터에 맞게 추가 학습하는 과정이다.\n"
             "핵심: 이미 학습된 일반 능력을 바탕으로 도메인 적응을 한다.\n"
             "예시: 의료영상 설명에 맞춰 기존 언어모델을 추가 학습하는 경우가 있다.\n"
             "한줄요약: 기존 모델을 목적에 맞게 조정하는 단계이다."}
        ]
    }
]

test_samples = [
    {
        "messages": [
            {"role": "user", "content": "Transformer를 쉽게 설명해줘."},
            {"role": "assistant", "content":
             "정의: Transformer는 attention을 중심으로 문맥 관계를 학습하는 신경망 구조이다.\n"
             "핵심: 순차 처리 없이도 각 위치 사이 관계를 효율적으로 다룰 수 있다.\n"
             "예시: 번역, 요약, 질의응답 등에 널리 쓰인다.\n"
             "한줄요약: attention 기반의 대표적인 언어모델 구조이다."}
        ]
    }
]

for name, data in [("train", train_samples), ("valid", valid_samples), ("test", test_samples)]:
    with open(f"qwen35_qlora_data/{name}.jsonl", "w", encoding="utf-8") as f:
        for row in data:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

print("데이터 저장 완료")

데이터 저장 완료

In [ ]:
# 학습 전 출력 먼저 확인

messages = [
    {"role": "system", "content": "You are a clear and patient teacher."},
    {"role": "user", "content": "Transformer를 쉽게 설명해줘."}
]

prompt = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True
)

before_out = generate(
    model,
    tokenizer,
    prompt=prompt,
    max_tokens=160
)

print(before_out)

Thinking Process:

1.  **Analyze the Request:**
    *   **Topic:** Transformer (AI model architecture).
    *   **Task:** Explain it simply (쉽게 설명해줘).
    *   **Role:** Clear and patient teacher (명확하고 인내심 있는 선생님).
    *   **Language:** Korean.

2.  **Determine the Target Audience:**
    *   Someone asking for a simple explanation likely wants an analogy or a high-level overview without getting bogged down in complex math (attention mechanisms, self-attention, positional encoding, etc., though mentioning them briefly adds depth).
    *   The tone should be encouraging, structured, and easy to follow.

3.  **Key Concepts to Cover:**
    *

In [ ]:
# QLoRA 학습

!mlx_lm.lora \
    --model mlx-community/Qwen3.5-4B-MLX-4bit \
    --train \
    --data qwen35_qlora_data \
    --adapter-path qwen35_adapters_exp1 \
    --batch-size 1 \
    --iters 200 \
    --steps-per-report 10 \
    --steps-per-eval 20 \
    --save-every 50 \
    --learning-rate 1e-4 \
    --mask-prompt

Loading pretrained model
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 10 files: 100%|██████████████████████| 10/10 [00:00<00:00, 9008.38it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading datasets
Training
Trainable parameters: 0.193% (8.116M/4205.750M)
Starting training..., iters: 200
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.06it/s]
Iter 1: Val loss 2.912, Val took 0.249s
Iter 10: Train loss 1.264, Learning Rate 1.000e-04, It/sec 0.558, Tokens/sec 49.274, Trained Tokens 883, Peak mem 10.140 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.84it/s]
Iter 20: Val loss 3.388, Val took 0.212s
Iter 20: Train loss 0.401, Learning Rate 1.000e-04, It/sec 0.707, Tokens/sec 62.668, Trained Tokens 1770, Peak mem 10.140 GB
Iter 30: Train loss 0.363, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 63.459, Trained Tokens 2664, Peak mem 10.140 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.13it/s]
Iter 40: Val loss 4.621, Val took 0.198s
Iter 40: Train loss 0.282, Learning Rate 1.000e-04, It/sec 0.709, Tokens/sec 62.133, Trained Tokens 3540, Peak mem 10.140 GB
Iter 50: Train loss 0.531, Learning Rate 1.000e-04, It/sec 0.704, Tokens/sec 62.408, Trained Tokens 4427, Peak mem 10.150 GB
Iter 50: Saved adapter weights to qwen35_adapters_exp1/adapters.safetensors and qwen35_adapters_exp1/0000050_adapters.safetensors.
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.14it/s]
Iter 60: Val loss 3.894, Val took 0.198s
Iter 60: Train loss 0.236, Learning Rate 1.000e-04, It/sec 0.708, Tokens/sec 62.497, Trained Tokens 5310, Peak mem 10.173 GB
Iter 70: Train loss 0.109, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 62.172, Trained Tokens 6186, Peak mem 10.173 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.94it/s]
Iter 80: Val loss 4.130, Val took 0.205s
Iter 80: Train loss 0.075, Learning Rate 1.000e-04, It/sec 0.709, Tokens/sec 63.426, Trained Tokens 7080, Peak mem 10.173 GB
Iter 90: Train loss 0.140, Learning Rate 1.000e-04, It/sec 0.707, Tokens/sec 62.683, Trained Tokens 7967, Peak mem 10.173 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.88it/s]
Iter 100: Val loss 4.058, Val took 0.208s
Iter 100: Train loss 0.114, Learning Rate 1.000e-04, It/sec 0.707, Tokens/sec 62.427, Trained Tokens 8850, Peak mem 10.173 GB
Iter 100: Saved adapter weights to qwen35_adapters_exp1/adapters.safetensors and qwen35_adapters_exp1/0000100_adapters.safetensors.
Iter 110: Train loss 0.045, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 63.097, Trained Tokens 9739, Peak mem 10.173 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.14it/s]
Iter 120: Val loss 4.716, Val took 0.198s
Iter 120: Train loss 0.005, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 62.522, Trained Tokens 10620, Peak mem 10.173 GB
Iter 130: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 63.010, Trained Tokens 11507, Peak mem 10.174 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.12it/s]
Iter 140: Val loss 4.881, Val took 0.198s
Iter 140: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 62.684, Trained Tokens 12390, Peak mem 10.174 GB
Iter 150: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.707, Tokens/sec 63.180, Trained Tokens 13284, Peak mem 10.174 GB
Iter 150: Saved adapter weights to qwen35_adapters_exp1/adapters.safetensors and qwen35_adapters_exp1/0000150_adapters.safetensors.
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.22it/s]
Iter 160: Val loss 4.816, Val took 0.195s
Iter 160: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.707, Tokens/sec 61.950, Trained Tokens 14160, Peak mem 10.174 GB
Iter 170: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 62.164, Trained Tokens 15036, Peak mem 10.174 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.17it/s]
Iter 180: Val loss 4.735, Val took 0.196s
Iter 180: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 63.596, Trained Tokens 15930, Peak mem 10.174 GB
Iter 190: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.708, Tokens/sec 62.911, Trained Tokens 16819, Peak mem 10.174 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.91it/s]
Iter 200: Val loss 4.655, Val took 0.207s
Iter 200: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 62.635, Trained Tokens 17700, Peak mem 10.174 GB
Iter 200: Saved adapter weights to qwen35_adapters_exp1/adapters.safetensors and qwen35_adapters_exp1/0000200_adapters.safetensors.
Saved final weights to qwen35_adapters_exp1/adapters.safetensors.

- --model: 4-bit 양자화된 베이스 모델
- --train: 학습 시작
- --data: train/valid/test JSONL 디렉터리
- --adapter-path: 저장될 adapter 경로
- --batch-size 1: M4 Pro에서 가장 안전한 시작점
- --iters 200: 작게 실험
- --mask-prompt: 보통 답변 부분 중심 학습에 유리
- --learning-rate 1e-4: 무난한 시작값

In [ ]:
# 학습 후 생성

prompt = """<|im_start|>system
You are a clear and patient teacher.
<|im_end|>
<|im_start|>user
Transformer를 쉽게 설명해줘.
<|im_end|>
<|im_start|>assistant
"""

!mlx_lm.generate \
    --model mlx-community/Qwen3.5-4B-MLX-4bit \
    --adapter-path qwen35_adapters_exp1 \
    --prompt "$prompt"

Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 10 files: 100%|█████████████████████| 10/10 [00:00<00:00, 18172.89it/s]
Download complete: : 0.00B [00:00, ?B/s]
==========
</think>

정의: Transformer는 각 토큰이 다른 토큰을 얼마나 참고할지 계산하는 메커니즘이다.
핵심: 문맥상 중요한 단어에 더 큰 가중치를 줄 수 있다.
예시: 문장 안에서 어떤 단어가 현재 단어 해석에 중요한지 수치적으로 반영한다.
한줄요약: 어떤 정보에 집중할지를 정하는 계산이다.
==========
Prompt: 39 tokens, 236.444 tokens-per-sec
Generation: 90 tokens, 60.101 tokens-per-sec
Peak memory: 2.689 GB

In [ ]:
import subprocess

messages = [
    {"role": "system", "content": "You are a clear and patient teacher."},
    {"role": "user", "content": "Transformer를 쉽게 설명해줘."}
]

prompt = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

print(type(prompt))
print("===== BASE MODEL =====")
base_out = generate(
    model,
    tokenizer,
    prompt=prompt,
    max_tokens=160
)
print(base_out)

print("\n===== QLoRA MODEL =====")
result = subprocess.run(
    [
        "mlx_lm.generate",
        "--model", "mlx-community/Qwen3.5-4B-MLX-4bit",
        "--adapter-path", "qwen35_adapters_exp1",
        "--prompt", prompt
    ],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

<class 'str'>
===== BASE MODEL =====
Thinking Process:

1.  **Analyze the Request:**
    *   **Topic:** Transformer (AI model architecture).
    *   **Task:** Explain it simply (쉽게 설명해줘).
    *   **Role:** Clear and patient teacher (명확하고 인내심 있는 선생님).
    *   **Language:** Korean.

2.  **Determine the Target Audience:**
    *   Someone asking for a simple explanation likely wants an analogy or a high-level overview without getting bogged down in complex math (attention mechanisms, self-attention, positional encoding, etc., though mentioning them briefly adds depth).
    *   The tone should be encouraging, structured, and easy to follow.

3.  **Key Concepts to Cover:**
    *

===== QLoRA MODEL =====
==========
</think>

정의: Transformer는 각 토큰이 다른 토큰을 얼마나 참고할지 계산하는 메커니즘이다.
핵심: 문맥상 중요한 단어에 더 큰 가중치를 줄 수 있다.
예시: 문장 안에서 어떤 단어가 현재 단어 해석에 중요한지 수치적으로 반영한다.
한줄요약: 어떤 정보에 집중할지를 정하는 계산이다.
==========
Prompt: 39 tokens, 244.054 tokens-per-sec
Generation: 90 tokens, 60.018 tokens-per-sec
Peak memory: 2.677 GB


Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]
Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 10407.70it/s]

In [ ]:
# 심화 실험: mask_prompt 비교

!mlx_lm.lora \
    --model mlx-community/Qwen3.5-4B-MLX-4bit \
    --train \
    --data qwen35_qlora_data \
    --adapter-path qwen35_adapters_no_mask \
    --batch-size 1 \
    --iters 200 \
    --steps-per-report 10 \
    --steps-per-eval 20 \
    --save-every 50 \
    --learning-rate 1e-4

Loading pretrained model
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 10 files: 100%|█████████████████████| 10/10 [00:00<00:00, 10821.22it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading datasets
Training
Trainable parameters: 0.193% (8.116M/4205.750M)
Starting training..., iters: 200
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.75it/s]
Iter 1: Val loss 2.835, Val took 0.213s
Iter 10: Train loss 1.199, Learning Rate 1.000e-04, It/sec 0.599, Tokens/sec 63.211, Trained Tokens 1056, Peak mem 10.140 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.92it/s]
Iter 20: Val loss 3.186, Val took 0.206s
Iter 20: Train loss 0.406, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 75.214, Trained Tokens 2115, Peak mem 10.145 GB
Iter 30: Train loss 0.349, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 75.755, Trained Tokens 3180, Peak mem 10.145 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.22it/s]
Iter 40: Val loss 3.642, Val took 0.194s
Iter 40: Train loss 0.216, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 74.694, Trained Tokens 4230, Peak mem 10.145 GB
Iter 50: Train loss 0.118, Learning Rate 1.000e-04, It/sec 0.712, Tokens/sec 75.395, Trained Tokens 5289, Peak mem 10.145 GB
Iter 50: Saved adapter weights to qwen35_adapters_no_mask/adapters.safetensors and qwen35_adapters_no_mask/0000050_adapters.safetensors.
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.24it/s]
Iter 60: Val loss 3.849, Val took 0.194s
Iter 60: Train loss 0.101, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 75.083, Trained Tokens 6345, Peak mem 10.172 GB
Iter 70: Train loss 0.063, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 74.647, Trained Tokens 7395, Peak mem 10.172 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.16it/s]
Iter 80: Val loss 3.766, Val took 0.197s
Iter 80: Train loss 0.119, Learning Rate 1.000e-04, It/sec 0.709, Tokens/sec 75.468, Trained Tokens 8460, Peak mem 10.177 GB
Iter 90: Train loss 0.093, Learning Rate 1.000e-04, It/sec 0.708, Tokens/sec 75.025, Trained Tokens 9519, Peak mem 10.177 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.15it/s]
Iter 100: Val loss 3.889, Val took 0.197s
Iter 100: Train loss 0.056, Learning Rate 1.000e-04, It/sec 0.708, Tokens/sec 74.779, Trained Tokens 10575, Peak mem 10.177 GB
Iter 100: Saved adapter weights to qwen35_adapters_no_mask/adapters.safetensors and qwen35_adapters_no_mask/0000100_adapters.safetensors.
Iter 110: Train loss 0.164, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 75.370, Trained Tokens 11637, Peak mem 10.177 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.89it/s]
Iter 120: Val loss 4.447, Val took 0.207s
Iter 120: Train loss 0.036, Learning Rate 1.000e-04, It/sec 0.709, Tokens/sec 74.653, Trained Tokens 12690, Peak mem 10.177 GB
Iter 130: Train loss 0.063, Learning Rate 1.000e-04, It/sec 0.708, Tokens/sec 75.021, Trained Tokens 13749, Peak mem 10.177 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.16it/s]
Iter 140: Val loss 4.466, Val took 0.197s
Iter 140: Train loss 0.065, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 75.033, Trained Tokens 14805, Peak mem 10.177 GB
Iter 150: Train loss 0.029, Learning Rate 1.000e-04, It/sec 0.709, Tokens/sec 75.552, Trained Tokens 15870, Peak mem 10.177 GB
Iter 150: Saved adapter weights to qwen35_adapters_no_mask/adapters.safetensors and qwen35_adapters_no_mask/0000150_adapters.safetensors.
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.19it/s]
Iter 160: Val loss 4.175, Val took 0.195s
Iter 160: Train loss 0.035, Learning Rate 1.000e-04, It/sec 0.707, Tokens/sec 74.189, Trained Tokens 16920, Peak mem 10.177 GB
Iter 170: Train loss 0.022, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 74.520, Trained Tokens 17970, Peak mem 10.177 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.21it/s]
Iter 180: Val loss 3.785, Val took 0.195s
Iter 180: Train loss 0.016, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 75.670, Trained Tokens 19035, Peak mem 10.177 GB
Iter 190: Train loss 0.015, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 75.393, Trained Tokens 20097, Peak mem 10.177 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.15it/s]
Iter 200: Val loss 3.689, Val took 0.197s
Iter 200: Train loss 0.015, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 74.763, Trained Tokens 21150, Peak mem 10.177 GB
Iter 200: Saved adapter weights to qwen35_adapters_no_mask/adapters.safetensors and qwen35_adapters_no_mask/0000200_adapters.safetensors.
Saved final weights to qwen35_adapters_no_mask/adapters.safetensors.

- qwen35_adapters_exp1: --mask-prompt 사용
- qwen35_adapters_no_mask: 미사용

- mask_prompt를 켠 쪽이 답변 형식 학습에 더 집중하는 경향

In [ ]:
# 심화: layer 수 줄이기

!mlx_lm.lora \
    --model mlx-community/Qwen3.5-4B-MLX-4bit \
    --train \
    --data qwen35_qlora_data \
    --adapter-path qwen35_adapters_4layers \
    --batch-size 1 \
    --iters 200 \
    --learning-rate 1e-4 \
    --mask-prompt \
    --num-layers 4

Loading pretrained model
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 10 files: 100%|█████████████████████| 10/10 [00:00<00:00, 15703.12it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading datasets
Training
Trainable parameters: 0.048% (2.029M/4205.750M)
Starting training..., iters: 200
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.94it/s]
Iter 1: Val loss 2.912, Val took 0.205s
Iter 10: Train loss 1.172, Learning Rate 1.000e-04, It/sec 1.056, Tokens/sec 93.226, Trained Tokens 883, Peak mem 4.723 GB
Iter 20: Train loss 0.189, Learning Rate 1.000e-04, It/sec 1.235, Tokens/sec 109.506, Trained Tokens 1770, Peak mem 4.725 GB
Iter 30: Train loss 0.062, Learning Rate 1.000e-04, It/sec 1.231, Tokens/sec 110.076, Trained Tokens 2664, Peak mem 4.725 GB
Iter 40: Train loss 0.123, Learning Rate 1.000e-04, It/sec 1.234, Tokens/sec 108.128, Trained Tokens 3540, Peak mem 4.725 GB
Iter 50: Train loss 0.067, Learning Rate 1.000e-04, It/sec 1.236, Tokens/sec 109.671, Trained Tokens 4427, Peak mem 4.725 GB
Iter 60: Train loss 0.036, Learning Rate 1.000e-04, It/sec 1.233, Tokens/sec 108.878, Trained Tokens 5310, Peak mem 4.725 GB
Iter 70: Train loss 0.006, Learning Rate 1.000e-04, It/sec 1.229, Tokens/sec 107.645, Trained Tokens 6186, Peak mem 4.725 GB
Iter 80: Train loss 0.018, Learning Rate 1.000e-04, It/sec 1.237, Tokens/sec 110.581, Trained Tokens 7080, Peak mem 4.725 GB
Iter 90: Train loss 0.015, Learning Rate 1.000e-04, It/sec 1.231, Tokens/sec 109.174, Trained Tokens 7967, Peak mem 4.725 GB
Iter 100: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.233, Tokens/sec 108.894, Trained Tokens 8850, Peak mem 4.725 GB
Iter 100: Saved adapter weights to qwen35_adapters_4layers/adapters.safetensors and qwen35_adapters_4layers/0000100_adapters.safetensors.
Iter 110: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.235, Tokens/sec 109.752, Trained Tokens 9739, Peak mem 4.731 GB
Iter 120: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.235, Tokens/sec 108.825, Trained Tokens 10620, Peak mem 4.733 GB
Iter 130: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.235, Tokens/sec 109.568, Trained Tokens 11507, Peak mem 4.733 GB
Iter 140: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.247, Tokens/sec 110.070, Trained Tokens 12390, Peak mem 4.733 GB
Iter 150: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.241, Tokens/sec 110.943, Trained Tokens 13284, Peak mem 4.735 GB
Iter 160: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.237, Tokens/sec 108.379, Trained Tokens 14160, Peak mem 4.735 GB
Iter 170: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.236, Tokens/sec 108.293, Trained Tokens 15036, Peak mem 4.735 GB
Iter 180: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.240, Tokens/sec 110.897, Trained Tokens 15930, Peak mem 4.735 GB
Iter 190: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.234, Tokens/sec 109.716, Trained Tokens 16819, Peak mem 4.735 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.39it/s]
Iter 200: Val loss 3.518, Val took 0.188s
Iter 200: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.237, Tokens/sec 109.002, Trained Tokens 17700, Peak mem 4.735 GB
Iter 200: Saved adapter weights to qwen35_adapters_4layers/adapters.safetensors and qwen35_adapters_4layers/0000200_adapters.safetensors.
Saved final weights to qwen35_adapters_4layers/adapters.safetensors.

In [ ]:
!mlx_lm.lora \
    --model mlx-community/Qwen3.5-4B-MLX-4bit \
    --train \
    --data qwen35_qlora_data \
    --adapter-path qwen35_adapters_8layers \
    --batch-size 1 \
    --iters 200 \
    --learning-rate 1e-4 \
    --mask-prompt \
    --num-layers 8

Loading pretrained model
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 10 files: 100%|█████████████████████| 10/10 [00:00<00:00, 10810.06it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading datasets
Training
Trainable parameters: 0.096% (4.058M/4205.750M)
Starting training..., iters: 200
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.85it/s]
Iter 1: Val loss 2.912, Val took 0.209s
Iter 10: Train loss 1.165, Learning Rate 1.000e-04, It/sec 0.864, Tokens/sec 76.270, Trained Tokens 883, Peak mem 6.519 GB
Iter 20: Train loss 0.322, Learning Rate 1.000e-04, It/sec 1.007, Tokens/sec 89.342, Trained Tokens 1770, Peak mem 6.519 GB
Iter 30: Train loss 0.212, Learning Rate 1.000e-04, It/sec 1.003, Tokens/sec 89.696, Trained Tokens 2664, Peak mem 6.519 GB
Iter 40: Train loss 0.140, Learning Rate 1.000e-04, It/sec 1.008, Tokens/sec 88.272, Trained Tokens 3540, Peak mem 6.519 GB
Iter 50: Train loss 0.064, Learning Rate 1.000e-04, It/sec 1.003, Tokens/sec 88.990, Trained Tokens 4427, Peak mem 6.519 GB
Iter 60: Train loss 0.053, Learning Rate 1.000e-04, It/sec 1.004, Tokens/sec 88.693, Trained Tokens 5310, Peak mem 6.519 GB
Iter 70: Train loss 0.172, Learning Rate 1.000e-04, It/sec 1.005, Tokens/sec 88.038, Trained Tokens 6186, Peak mem 6.519 GB
Iter 80: Train loss 0.137, Learning Rate 1.000e-04, It/sec 1.007, Tokens/sec 90.035, Trained Tokens 7080, Peak mem 6.519 GB
Iter 90: Train loss 0.204, Learning Rate 1.000e-04, It/sec 1.006, Tokens/sec 89.200, Trained Tokens 7967, Peak mem 6.519 GB
Iter 100: Train loss 0.177, Learning Rate 1.000e-04, It/sec 1.002, Tokens/sec 88.515, Trained Tokens 8850, Peak mem 6.519 GB
Iter 100: Saved adapter weights to qwen35_adapters_8layers/adapters.safetensors and qwen35_adapters_8layers/0000100_adapters.safetensors.
Iter 110: Train loss 0.192, Learning Rate 1.000e-04, It/sec 1.001, Tokens/sec 89.003, Trained Tokens 9739, Peak mem 6.535 GB
Iter 120: Train loss 0.275, Learning Rate 1.000e-04, It/sec 1.006, Tokens/sec 88.662, Trained Tokens 10620, Peak mem 6.535 GB
Iter 130: Train loss 0.201, Learning Rate 1.000e-04, It/sec 1.003, Tokens/sec 88.951, Trained Tokens 11507, Peak mem 6.535 GB
Iter 140: Train loss 0.132, Learning Rate 1.000e-04, It/sec 1.001, Tokens/sec 88.425, Trained Tokens 12390, Peak mem 6.535 GB
Iter 150: Train loss 0.165, Learning Rate 1.000e-04, It/sec 1.006, Tokens/sec 89.927, Trained Tokens 13284, Peak mem 6.535 GB
Iter 160: Train loss 0.015, Learning Rate 1.000e-04, It/sec 1.005, Tokens/sec 88.030, Trained Tokens 14160, Peak mem 6.535 GB
Iter 170: Train loss 0.003, Learning Rate 1.000e-04, It/sec 1.007, Tokens/sec 88.203, Trained Tokens 15036, Peak mem 6.535 GB
Iter 180: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.002, Tokens/sec 89.549, Trained Tokens 15930, Peak mem 6.535 GB
Iter 190: Train loss 0.000, Learning Rate 1.000e-04, It/sec 1.004, Tokens/sec 89.236, Trained Tokens 16819, Peak mem 6.535 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.26it/s]
Iter 200: Val loss 4.038, Val took 0.193s
Iter 200: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.999, Tokens/sec 87.976, Trained Tokens 17700, Peak mem 6.535 GB
Iter 200: Saved adapter weights to qwen35_adapters_8layers/adapters.safetensors and qwen35_adapters_8layers/0000200_adapters.safetensors.
Saved final weights to qwen35_adapters_8layers/adapters.safetensors.

- 4 layers: 가볍지만 변화가 약할 수 있음
- 8 layers: 대체로 균형형
- 기본/더 많은 layers: 적응 강도는 올라가지만 자원 사용 증가

In [ ]:
#심화: gradient checkpoint 메모리 절약

!mlx_lm.lora \
    --model mlx-community/Qwen3.5-4B-MLX-4bit \
    --train \
    --data qwen35_qlora_data \
    --adapter-path qwen35_adapters_ckpt \
    --batch-size 1 \
    --iters 200 \
    --learning-rate 1e-4 \
    --mask-prompt \
    --grad-checkpoint

Loading pretrained model
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 10 files: 100%|█████████████████████| 10/10 [00:00<00:00, 13009.63it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading datasets
Training
Trainable parameters: 0.193% (8.116M/4205.750M)
Starting training..., iters: 200
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  4.54it/s]
Iter 1: Val loss 2.912, Val took 0.222s
Iter 10: Train loss 1.264, Learning Rate 1.000e-04, It/sec 0.579, Tokens/sec 51.124, Trained Tokens 883, Peak mem 4.062 GB
Iter 20: Train loss 0.401, Learning Rate 1.000e-04, It/sec 0.712, Tokens/sec 63.161, Trained Tokens 1770, Peak mem 4.062 GB
Iter 30: Train loss 0.363, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 63.571, Trained Tokens 2664, Peak mem 4.062 GB
Iter 40: Train loss 0.282, Learning Rate 1.000e-04, It/sec 0.710, Tokens/sec 62.203, Trained Tokens 3540, Peak mem 4.062 GB
Iter 50: Train loss 0.531, Learning Rate 1.000e-04, It/sec 0.713, Tokens/sec 63.251, Trained Tokens 4427, Peak mem 4.062 GB
Iter 60: Train loss 0.236, Learning Rate 1.000e-04, It/sec 0.714, Tokens/sec 63.005, Trained Tokens 5310, Peak mem 4.062 GB
Iter 70: Train loss 0.109, Learning Rate 1.000e-04, It/sec 0.715, Tokens/sec 62.659, Trained Tokens 6186, Peak mem 4.062 GB
Iter 80: Train loss 0.075, Learning Rate 1.000e-04, It/sec 0.714, Tokens/sec 63.792, Trained Tokens 7080, Peak mem 4.062 GB
Iter 90: Train loss 0.140, Learning Rate 1.000e-04, It/sec 0.714, Tokens/sec 63.335, Trained Tokens 7967, Peak mem 4.062 GB
Iter 100: Train loss 0.114, Learning Rate 1.000e-04, It/sec 0.712, Tokens/sec 62.857, Trained Tokens 8850, Peak mem 4.062 GB
Iter 100: Saved adapter weights to qwen35_adapters_ckpt/adapters.safetensors and qwen35_adapters_ckpt/0000100_adapters.safetensors.
Iter 110: Train loss 0.045, Learning Rate 1.000e-04, It/sec 0.714, Tokens/sec 63.518, Trained Tokens 9739, Peak mem 4.100 GB
Iter 120: Train loss 0.005, Learning Rate 1.000e-04, It/sec 0.713, Tokens/sec 62.852, Trained Tokens 10620, Peak mem 4.100 GB
Iter 130: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.713, Tokens/sec 63.270, Trained Tokens 11507, Peak mem 4.100 GB
Iter 140: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.711, Tokens/sec 62.824, Trained Tokens 12390, Peak mem 4.100 GB
Iter 150: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.713, Tokens/sec 63.739, Trained Tokens 13284, Peak mem 4.100 GB
Iter 160: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.713, Tokens/sec 62.494, Trained Tokens 14160, Peak mem 4.100 GB
Iter 170: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.714, Tokens/sec 62.580, Trained Tokens 15036, Peak mem 4.100 GB
Iter 180: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.713, Tokens/sec 63.755, Trained Tokens 15930, Peak mem 4.100 GB
Iter 190: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.713, Tokens/sec 63.380, Trained Tokens 16819, Peak mem 4.105 GB
Calculating loss...: 100%|████████████████████████| 1/1 [00:00<00:00,  5.12it/s]
Iter 200: Val loss 4.655, Val took 0.198s
Iter 200: Train loss 0.000, Learning Rate 1.000e-04, It/sec 0.714, Tokens/sec 62.931, Trained Tokens 17700, Peak mem 4.105 GB
Iter 200: Saved adapter weights to qwen35_adapters_ckpt/adapters.safetensors and qwen35_adapters_ckpt/0000200_adapters.safetensors.
Saved final weights to qwen35_adapters_ckpt/adapters.safetensors.

- 메모리 사용량을 줄이는 대신
- 계산을 다시 해서 속도는 다소 느려질 수 있음

In [ ]:
# 테스트 세트 perplexity 평가

!mlx_lm.lora \
    --model mlx-community/Qwen3.5-4B-MLX-4bit \
    --adapter-path qwen35_adapters_exp1 \
    --data qwen35_qlora_data \
    --test

Loading pretrained model
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 10 files: 100%|█████████████████████| 10/10 [00:00<00:00, 29167.62it/s]
Download complete: : 0.00B [00:00, ?B/s]
Loading datasets
Testing
Calculating loss...: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/opt/anaconda3/bin/mlx_lm.lora", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/mlx_lm/lora.py", line 369, in main
    run(types.SimpleNamespace(**args))
  File "/opt/anaconda3/lib/python3.11/site-packages/mlx_lm/lora.py", line 347, in run
    evaluate_model(args, model, test_set)
  File "/opt/anaconda3/lib/python3.11/site-packages/mlx_lm/lora.py", line 306, in evaluate_model
    test_loss = evaluate(
                ^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/mlx_lm/tuner/trainer.py", line 192, in evaluate
    for _, batch in tqdm(
  File "/opt/anaconda3/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/opt/anaconda3/lib/python3.11/site-packages/mlx_lm/tuner/trainer.py", line 117, in iterate_batches
    raise ValueError(
ValueError: Dataset must have at least batch_size=4 examples but only has 1.

perplexity는 낮을수록 보통 test 데이터 분포에 더 잘 맞는다는 뜻입니다.
다만 사람이 보기 좋은 답변과 완전히 일치하지는 않으므로, 정성 비교와 같이 봐야 함.

In [ ]:
import subprocess
import sys

test_questions = [
    "LoRA를 쉽게 설명해줘.",
    "QLoRA를 쉽게 설명해줘.",
    "Attention을 쉽게 설명해줘.",
    "Transformer를 쉽게 설명해줘.",
    "양자화의 장점을 설명해줘."
]

for q in test_questions:
    messages = [
        {"role": "system", "content": "You are a clear and patient teacher."},
        {"role": "user", "content": q}
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    print("=" * 80)
    print("질문:", q)

    print("\n[BASE]")
    base_out = generate(
        model,
        tokenizer,
        prompt=prompt,
        max_tokens=160
    )
    print(base_out)

    print("\n[QLoRA]")
    result = subprocess.run(
        [
            sys.executable, "-m", "mlx_lm.generate",
            "--model", "mlx-community/Qwen3.5-4B-MLX-4bit",
            "--adapter-path", "qwen35_adapters_exp1",
            "--prompt", prompt
        ],
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print("실행 오류:")
        print(result.stderr)
    else:
        print(result.stdout)

================================================================================
질문: LoRA를 쉽게 설명해줘.

[BASE]
Thinking Process:

1.  **Analyze the Request:**
    *   **Topic:** LoRA (Low-Rank Adaptation).
    *   **Goal:** Explain it simply (쉽게 설명해줘).
    *   **Role:** Clear and patient teacher (명확하고 인내심 있는 선생님).
    *   **Language:** Korean.

2.  **Determine the Core Concept:**
    *   What is LoRA? It's a technique for fine-tuning large language models (LLMs) efficiently.
    *   Key analogy: Adding a small lens to a camera, or a sidekick to a main character, or a shortcut in a long road.
    *   Key problem it solves: Fine-tuning the entire model is

[QLoRA]
Calling `python -m mlx_lm.generate...` directly is deprecated. Use `mlx_lm.generate...` or `python -m mlx_lm generate ...` instead.
==========
</think>

정의: LoRA는 큰 모델 전체를 다시 학습하지 않고 작은 저랭크 adapter만 학습하는 방법이다.
핵심: 전체 가중치를 모두 업데이트하지 않아서 메모리와 계산량을 줄일 수 있다.
예시: 원래 모델은 그대로 두고, 특정 태스크에 맞는 작은 보정만 추가하는 방식이다.
한줄요약: 적은 비용으로 미세조정을 가능하게 하는 기법이다.
==========
Prompt: 40 tokens, 247.904 tokens-per-sec
Generation: 92 tokens, 60.562 tokens-per-sec
Peak memory: 2.695 GB

================================================================================
질문: QLoRA를 쉽게 설명해줘.

[BASE]
Thinking Process:

1.  **Analyze the Request:**
    *   **Topic:** QLoRA (Quantized Low-Rank Adaptation).
    *   **Task:** Explain it simply (쉽게 설명해줘).
    *   **Role:** Clear and patient teacher (명확하고 인내심 있는 선생님).
    *   **Language:** Korean.

2.  **Determine the Core Concept:**
    *   What is QLoRA? It's a technique to fine-tune large language models (LLMs) efficiently.
    *   Key components:
        *   **LoRA (Low-Rank Adaptation):** A method to fine-tune models by updating only a small part of the weights (low-rank matrices) instead

[QLoRA]
Calling `python -m mlx_lm.generate...` directly is deprecated. Use `mlx_lm.generate...` or `python -m mlx_lm generate ...` instead.
==========
</think>

정의: QLoRA는 양자화된 베이스 모델 위에서 LoRA adapter만 학습하는 미세조정 방법이다.
핵심: 베이스 모델을 4-bit처럼 더 가볍게 저장하여 메모리를 절약한다.
예시: 큰 모델 본체는 고정하고, 작은 adapter만 학습한다.
한줄요약: LoRA를 더 적은 메모리로 수행하게 해주는 방법이다.
==========
Prompt: 41 tokens, 252.705 tokens-per-sec
Generation: 85 tokens, 60.659 tokens-per-sec
Peak memory: 2.699 GB

================================================================================
질문: Attention을 쉽게 설명해줘.

[BASE]
Thinking Process:

1.  **Analyze the Request:**
    *   **Topic:** Attention (주의, 집중).
    *   **Task:** Explain it simply (쉽게 설명해줘).
    *   **Role:** Clear and patient teacher (명확하고 인내심 있는 선생님).
    *   **Language:** Korean.

2.  **Determine the Core Concept:**
    *   What is "Attention"? It's the cognitive process of selecting specific information from a vast amount of available information.
    *   Analogy time: A spotlight, a camera lens, a radio, a flashlight.
    *   Key aspects: Focus, filtering, prioritization, concentration.

3.  **Drafting the Explanation (Iterative Process):**

[QLoRA]
Calling `python -m mlx_lm.generate...` directly is deprecated. Use `mlx_lm.generate...` or `python -m mlx_lm generate ...` instead.
==========
</think>

정의: Attention은 각 토큰이 다른 토큰을 얼마나 참고할지 계산하는 메커니즘이다.
핵심: 문맥상 중요한 단어에 더 큰 가중치를 줄 수 있다.
예시: 문장 안에서 어떤 단어가 현재 단어 해석에 중요한지 수치적으로 반영한다.
한줄요약: 어떤 정보에 집중할지를 정하는 계산이다.
==========
Prompt: 39 tokens, 244.501 tokens-per-sec
Generation: 90 tokens, 60.524 tokens-per-sec
Peak memory: 2.666 GB

================================================================================
질문: Transformer를 쉽게 설명해줘.

[BASE]
Thinking Process:

1.  **Analyze the Request:**
    *   **Topic:** Transformer (AI model architecture).
    *   **Task:** Explain it simply (쉽게 설명해줘).
    *   **Role:** Clear and patient teacher (명확하고 인내심 있는 선생님).
    *   **Language:** Korean.

2.  **Determine the Target Audience:**
    *   Someone asking for a simple explanation likely wants an analogy or a high-level overview without getting bogged down in complex math (attention mechanisms, self-attention, positional encoding, etc., though mentioning them briefly adds depth).
    *   The tone should be encouraging, structured, and easy to follow.

3.  **Key Concepts to Cover:**
    *

[QLoRA]
Calling `python -m mlx_lm.generate...` directly is deprecated. Use `mlx_lm.generate...` or `python -m mlx_lm generate ...` instead.
==========
</think>

정의: Transformer는 각 토큰이 다른 토큰을 얼마나 참고할지 계산하는 메커니즘이다.
핵심: 문맥상 중요한 단어에 더 큰 가중치를 줄 수 있다.
예시: 문장 안에서 어떤 단어가 현재 단어 해석에 중요한지 수치적으로 반영한다.
한줄요약: 어떤 정보에 집중할지를 정하는 계산이다.
==========
Prompt: 39 tokens, 248.233 tokens-per-sec
Generation: 90 tokens, 60.675 tokens-per-sec
Peak memory: 2.666 GB

================================================================================
질문: 양자화의 장점을 설명해줘.

[BASE]
Thinking Process:

1.  **Analyze the Request:**
    *   **Topic:** Advantages of Quantization (양자화의 장점).
    *   **Role:** Clear and patient teacher (명확하고 인내심 있는 선생님).
    *   **Language:** Korean.
    *   **Goal:** Explain the benefits of quantization in an easy-to-understand manner.

2.  **Determine the Context:**
    *   "Quantization" (양자화) can refer to different fields:
        *   **Quantum Physics:** Fundamental nature of energy/matter.
        *   **Digital Signal Processing/Image Processing:** Discretizing continuous signals.
        *   **Machine Learning:** Reducing model size/precision.


[QLoRA]
Calling `python -m mlx_lm.generate...` directly is deprecated. Use `mlx_lm.generate...` or `python -m mlx_lm generate ...` instead.
==========
</think>

정의: 양자화는 모델 수치 표현의 비트 수를 줄여 모델을 더 가볍게 만드는 기법이다.
핵심: 메모리 사용량과 추론 비용을 줄일 수 있다.
예시: float16 대신 4-bit 수준으로 가중치를 저장하는 식이다.
한줄요약: 모델을 작고 효율적으로 만드는 방법이다.
==========
Prompt: 41 tokens, 259.328 tokens-per-sec
Generation: 79 tokens, 60.678 tokens-per-sec
Peak memory: 2.699 GB